insert into employee (first_name, last_name, email, company_name, manager_id, position_title, start_date, is_manager, password, resume_id, id)
values  ('Stefan', 'Gordon', 'Stefan_Gordon@birdseyeentertainment.com', 'Birdseye Entertainment', null, 'CEO', '2005-02-20', 1, 'gordonst', null, 1),
        ('Elisha', 'Stanley', 'Elisha_Stanley@birdseyeentertainment.com', 'Birdseye Entertainment', 1, 'Engineering Manager', '2015-04-06', 1, 'stanleyel', null, 2),
        ('Edna', 'Robinson', 'Edna_Robinson@birdseyeentertainment.com', 'Birdseye Entertainment', 2, 'Engineering Manager', '1997-12-31', 1, 'robinsoned', null, 3),
        ('Lindsey', 'Hayes', 'Lindsey_Hayes@birdseyeentertainment.com', 'Birdseye Entertainment', 2, 'Engineering Manager', '1992-11-15', 1, 'hayesli', null, 4),
        ('Garfield', 'Eaton', 'Garfield_Eaton@birdseyeentertainment.com', 'Birdseye Entertainment', 1, 'Engineering Manager', '1997-08-05', 1, 'eatonga', null, 5),
        ('Jana', 'Benjamin', 'Jana_Benjamin@birdseyeentertainment.com', 'Birdseye Entertainment', 2, 'Engineering Manager', '2015-01-28', 1, 'benjaminja', null, 6),
        ('Toby', 'Duran', 'Toby_Duran@birdseyeentertainment.com', 'Birdseye Entertainment', 5, 'Engineering Manager', '1991-03-07', 1, 'duranto', null, 7),
        ('Myrtle', 'Davidson', 'Myrtle_Davidson@birdseyeentertainment.com', 'Birdseye Entertainment', 3, 'Engineering Manager', '2005-12-30', 1, 'davidsonmy', null, 8),
        ('Carol', 'Brennan', 'Carol_Brennan@birdseyeentertainment.com', 'Birdseye Entertainment', 7, 'Engineering Manager', '1991-09-19', 1, 'brennanca', null, 9),
        ('Esperanza', 'Ingram', 'Esperanza_Ingram@birdseyeentertainment.com', 'Birdseye Entertainment', 7, 'Engineering Manager', '2004-11-09', 1, 'ingrames', null, 10),
        ('Yesenia', 'Harper', 'Yesenia_Harper@birdseyeentertainment.com', 'Birdseye Entertainment', 1, 'Engineering Manager', '1997-11-12', 1, 'harperye', null, 11),
        ('Sally', 'Fitzpatrick', 'Sally_Fitzpatrick@birdseyeentertainment.com', 'Birdseye Entertainment', 7, 'Engineering Manager', '2015-04-10', 1, 'fitzpatricksa', null, 12),
        ('Olin', 'Schultz', 'Olin_Schultz@birdseyeentertainment.com', 'Birdseye Entertainment', 9, 'Engineering Manager', '1995-08-10', 1, 'schultzol', null, 13),
        ('Josephine', 'Roman', 'Josephine_Roman@birdseyeentertainment.com', 'Birdseye Entertainment', 5, 'Engineering Manager', '1991-11-30', 1, 'romanjo', null, 14),
        ('Lidia', 'Patterson', 'Lidia_Patterson@birdseyeentertainment.com', 'Birdseye Entertainment', 11, 'Engineering Manager', '1991-01-27', 1, 'pattersonli', null, 15),
        ('Lydia', 'Beasley', 'Lydia_Beasley@birdseyeentertainment.com', 'Birdseye Entertainment', 12, 'Engineering Manager', '1992-03-28', 1, 'beasleyly', null, 16),
        ('Myrna', 'Winters', 'Myrna_Winters@birdseyeentertainment.com', 'Birdseye Entertainment', 5, 'Engineering Manager', '2015-11-03', 1, 'wintersmy', null, 17),
        ('Lyle', 'Sherman', 'Lyle_Sherman@birdseyeentertainment.com', 'Birdseye Entertainment', 2, 'Engineering Manager', '1995-10-09', 1, 'shermanly', null, 18),
        ('Herman', 'Roberts', 'Herman_Roberts@birdseyeentertainment.com', 'Birdseye Entertainment', 3, 'Engineering Manager', '2016-02-02', 1, 'robertshe', null, 19),
        ('Erik', 'Chavez', 'Erik_Chavez@birdseyeentertainment.com', 'Birdseye Entertainment', 5, 'Engineering Manager', '2013-03-12', 1, 'chavezer', null, 20),
        ('Mattie', 'Compton', 'Mattie_Compton@birdseyeentertainment.com', 'Birdseye Entertainment', 5, 'Engineering Manager', '1991-03-04', 1, 'comptonma', null, 21),
        ('Dustin', 'Rivas', 'Dustin_Rivas@birdseyeentertainment.com', 'Birdseye Entertainment', 16, 'Engineering Manager', '1993-06-20', 1, 'rivasdu', null, 22),
        ('Justin', 'Valdez', 'Justin_Valdez@birdseyeentertainment.com', 'Birdseye Entertainment', 5, 'Engineering Manager', '2011-08-12', 1, 'valdezju', null, 23),
        ('Monroe', 'Valentine', 'Monroe_Valentine@birdseyeentertainment.com', 'Birdseye Entertainment', 10, 'Engineering Manager', '2009-04-24', 1, 'valentinemo', null, 24),
        ('Krista', 'Levy', 'Krista_Levy@birdseyeentertainment.com', 'Birdseye Entertainment', 5, 'Engineering Manager', '2002-09-10', 1, 'levykr', null, 25),
        ('Rosario', 'Bowen', 'Rosario_Bowen@birdseyeentertainment.com', 'Birdseye Entertainment', 16, 'Engineering Manager', '2016-08-03', 1, 'bowenro', null, 26),
        ('Stuart', 'Hughes', 'Stuart_Hughes@birdseyeentertainment.com', 'Birdseye Entertainment', 6, 'Engineering Manager', '2013-10-29', 1, 'hughesst', null, 27),
        ('Oscar', 'Manning', 'Oscar_Manning@birdseyeentertainment.com', 'Birdseye Entertainment', 1, 'Engineering Manager', '2009-09-08', 1, 'manningos', null, 28),
        ('Winford', 'Chang', 'Winford_Chang@birdseyeentertainment.com', 'Birdseye Entertainment', 16, 'Engineering Manager', '2015-02-12', 1, 'changwi', null, 29),
        ('Liliana', 'Frank', 'Liliana_Frank@birdseyeentertainment.com', 'Birdseye Entertainment', 15, 'Engineering Manager', '2006-04-09', 1, 'frankli', null, 30),
        ('Francesca', 'Mccoy', 'Francesca_Mccoy@birdseyeentertainment.com', 'Birdseye Entertainment', 26, 'Engineering Manager', '2015-07-01', 1, 'mccoyfr', null, 31),
        ('Justine', 'Leach', 'Justine_Leach@birdseyeentertainment.com', 'Birdseye Entertainment', 4, 'Engineering Manager', '2016-10-27', 1, 'leachju', null, 32),
        ('Arline', 'Mccoy', 'Arline_Mccoy@birdseyeentertainment.com', 'Birdseye Entertainment', 22, 'Engineering Manager', '1993-05-22', 1, 'mccoyar', null, 33),
        ('Chong', 'Collins', 'Chong_Collins@birdseyeentertainment.com', 'Birdseye Entertainment', 7, 'Engineering Manager', '2008-10-11', 1, 'collinsch', null, 34),
        ('Ryan', 'Shelton', 'Ryan_Shelton@birdseyeentertainment.com', 'Birdseye Entertainment', 14, 'Engineering Manager', '1998-06-16', 1, 'sheltonry', null, 35),
        ('Karyn', 'Prince', 'Karyn_Prince@birdseyeentertainment.com', 'Birdseye Entertainment', 6, 'Engineering Manager', '2008-09-15', 1, 'princeka', null, 36),
        ('Lucile', 'Mayo', 'Lucile_Mayo@birdseyeentertainment.com', 'Birdseye Entertainment', 24, 'Engineering Manager', '2003-06-28', 1, 'mayolu', null, 37),
        ('Ralph', 'Braun', 'Ralph_Braun@birdseyeentertainment.com', 'Birdseye Entertainment', 23, 'Engineering Manager', '2006-05-14', 1, 'braunra', null, 38),
        ('Edgar', 'Clements', 'Edgar_Clements@birdseyeentertainment.com', 'Birdseye Entertainment', 37, 'Engineering Manager', '2006-01-28', 1, 'clementsed', null, 39),
        ('Andrea', 'Mueller', 'Andrea_Mueller@birdseyeentertainment.com', 'Birdseye Entertainment', 8, 'Engineering Manager', '1996-12-07', 1, 'muelleran', null, 40),
        ('Hai', 'Giles', 'Hai_Giles@birdseyeentertainment.com', 'Birdseye Entertainment', 20, 'Engineering Manager', '2001-08-19', 1, 'gilesha', null, 41),
        ('Elva', 'Morris', 'Elva_Morris@birdseyeentertainment.com', 'Birdseye Entertainment', 34, 'Engineering Manager', '1999-01-01', 1, 'morrisel', null, 42),
        ('Christoper', 'Ferrell', 'Christoper_Ferrell@birdseyeentertainment.com', 'Birdseye Entertainment', 21, 'Engineering Manager', '1997-03-25', 1, 'ferrellch', null, 43),
        ('Jewel', 'Parks', 'Jewel_Parks@birdseyeentertainment.com', 'Birdseye Entertainment', 4, 'Engineering Manager', '2017-04-20', 1, 'parksje', null, 44),
        ('Maura', 'Harvey', 'Maura_Harvey@birdseyeentertainment.com', 'Birdseye Entertainment', 18, 'Engineering Manager', '2011-10-24', 1, 'harveyma', null, 45),
        ('Dino', 'Campbell', 'Dino_Campbell@birdseyeentertainment.com', 'Birdseye Entertainment', 16, 'Engineering Manager', '2011-10-01', 1, 'campbelldi', null, 46),
        ('Mckinley', 'Lindsey', 'Mckinley_Lindsey@birdseyeentertainment.com', 'Birdseye Entertainment', 11, 'Engineering Manager', '1995-09-06', 1, 'lindseymc', null, 47),
        ('Garret', 'Levine', 'Garret_Levine@birdseyeentertainment.com', 'Birdseye Entertainment', 16, 'Engineering Manager', '2003-08-11', 1, 'levinega', null, 48),
        ('Juliet', 'Nguyen', 'Juliet_Nguyen@birdseyeentertainment.com', 'Birdseye Entertainment', 40, 'Engineering Manager', '2005-12-30', 1, 'nguyenju', null, 49),
        ('Dianna', 'Rasmussen', 'Dianna_Rasmussen@birdseyeentertainment.com', 'Birdseye Entertainment', 29, 'Engineering Manager', '2007-11-12', 1, 'rasmussendi', null, 50),
        ('Bridget', 'Casey', 'Bridget_Casey@birdseyeentertainment.com', 'Birdseye Entertainment', 39, 'Engineering Manager', '1998-08-12', 1, 'caseybr', null, 51),
        ('Terry', 'Bolton', 'Terry_Bolton@birdseyeentertainment.com', 'Birdseye Entertainment', 48, 'Engineering Manager', '1999-04-02', 1, 'boltonte', null, 52),
        ('Laverne', 'Schultz', 'Laverne_Schultz@birdseyeentertainment.com', 'Birdseye Entertainment', 5, 'Engineering Manager', '1991-01-30', 1, 'schultzla', null, 53),
        ('Angeline', 'Haynes', 'Angeline_Haynes@birdseyeentertainment.com', 'Birdseye Entertainment', 17, 'Engineering Manager', '1997-11-18', 1, 'haynesan', null, 54),
        ('Elva', 'Sharp', 'Elva_Sharp@birdseyeentertainment.com', 'Birdseye Entertainment', 34, 'Engineering Manager', '1993-07-13', 1, 'sharpel', null, 55),
        ('Valeria', 'Newton', 'Valeria_Newton@birdseyeentertainment.com', 'Birdseye Entertainment', 8, 'Engineering Manager', '2012-12-20', 1, 'newtonva', null, 56),
        ('Ericka', 'Powers', 'Ericka_Powers@birdseyeentertainment.com', 'Birdseye Entertainment', 23, 'Engineering Manager', '2009-07-15', 1, 'powerser', null, 57),
        ('Jayson', 'Bowers', 'Jayson_Bowers@birdseyeentertainment.com', 'Birdseye Entertainment', 28, 'Engineering Manager', '2001-11-10', 1, 'bowersja', null, 58),
        ('Dexter', 'Beck', 'Dexter_Beck@birdseyeentertainment.com', 'Birdseye Entertainment', 17, 'Engineering Manager', '2007-06-02', 1, 'beckde', null, 59),
        ('Foster', 'Espinoza', 'Foster_Espinoza@birdseyeentertainment.com', 'Birdseye Entertainment', 32, 'Engineering Manager', '1991-06-24', 1, 'espinozafo', null, 60),
        ('Gaston', 'Castro', 'Gaston_Castro@birdseyeentertainment.com', 'Birdseye Entertainment', 55, 'Engineering Manager', '2006-02-12', 1, 'castroga', null, 61),
        ('Ruth', 'Francis', 'Ruth_Francis@birdseyeentertainment.com', 'Birdseye Entertainment', 37, 'Engineering Manager', '1993-05-07', 1, 'francisru', null, 62),
        ('Olive', 'Moss', 'Olive_Moss@birdseyeentertainment.com', 'Birdseye Entertainment', 56, 'Engineering Manager', '2002-07-02', 1, 'mossol', null, 63),
        ('Gayle', 'Hodges', 'Gayle_Hodges@birdseyeentertainment.com', 'Birdseye Entertainment', 47, 'Engineering Manager', '1994-05-21', 1, 'hodgesga', null, 64),
        ('Gina', 'Moss', 'Gina_Moss@birdseyeentertainment.com', 'Birdseye Entertainment', 14, 'Engineering Manager', '2005-12-01', 1, 'mossgi', null, 65),
        ('Gerard', 'Li', 'Gerard_Li@birdseyeentertainment.com', 'Birdseye Entertainment', 42, 'Engineering Manager', '2010-11-02', 1, 'lige', null, 66),
        ('Dwight', 'Day', 'Dwight_Day@birdseyeentertainment.com', 'Birdseye Entertainment', 22, 'Engineering Manager', '2005-06-02', 1, 'daydw', null, 67),
        ('Berry', 'Baker', 'Berry_Baker@birdseyeentertainment.com', 'Birdseye Entertainment', 20, 'Engineering Manager', '1997-04-22', 1, 'bakerbe', null, 68),
        ('Francisco', 'Torres', 'Francisco_Torres@birdseyeentertainment.com', 'Birdseye Entertainment', 5, 'Engineering Manager', '1995-09-01', 1, 'torresfr', null, 69),
        ('Shawn', 'Boyd', 'Shawn_Boyd@birdseyeentertainment.com', 'Birdseye Entertainment', 66, 'Engineering Manager', '2004-03-21', 1, 'boydsh', null, 70),
        ('Tamra', 'Soto', 'Tamra_Soto@birdseyeentertainment.com', 'Birdseye Entertainment', 68, 'Engineering Manager', '2011-08-01', 1, 'sotota', null, 71),
        ('Karyn', 'Brady', 'Karyn_Brady@birdseyeentertainment.com', 'Birdseye Entertainment', 9, 'Engineering Manager', '2013-07-10', 1, 'bradyka', null, 72),
        ('Ginger', 'Hays', 'Ginger_Hays@birdseyeentertainment.com', 'Birdseye Entertainment', 27, 'Engineering Manager', '1991-08-05', 1, 'haysgi', null, 73),
        ('Damion', 'Obrien', 'Damion_Obrien@birdseyeentertainment.com', 'Birdseye Entertainment', 55, 'Engineering Manager', '2014-10-25', 1, 'obrienda', null, 74),
        ('Barbra', 'Ferguson', 'Barbra_Ferguson@birdseyeentertainment.com', 'Birdseye Entertainment', 51, 'Engineering Manager', '1990-12-20', 1, 'fergusonba', null, 75),
        ('Mary', 'Mckee', 'Mary_Mckee@birdseyeentertainment.com', 'Birdseye Entertainment', 16, 'Engineering Manager', '1993-05-23', 1, 'mckeema', null, 76),
        ('Juliette', 'King', 'Juliette_King@birdseyeentertainment.com', 'Birdseye Entertainment', 48, 'Engineering Manager', '2011-11-10', 1, 'kingju', null, 77),
        ('Murray', 'Carrillo', 'Murray_Carrillo@birdseyeentertainment.com', 'Birdseye Entertainment', 21, 'Engineering Manager', '2005-09-10', 1, 'carrillomu', null, 78),
        ('Dean', 'Martin', 'Dean_Martin@birdseyeentertainment.com', 'Birdseye Entertainment', 74, 'Engineering Manager', '2015-05-27', 1, 'martinde', null, 79),
        ('Betty', 'Randall', 'Betty_Randall@birdseyeentertainment.com', 'Birdseye Entertainment', 46, 'Engineering Manager', '2005-10-16', 1, 'randallbe', null, 80),
        ('Freida', 'Salas', 'Freida_Salas@birdseyeentertainment.com', 'Birdseye Entertainment', 55, 'Engineering Manager', '1991-10-17', 1, 'salasfr', null, 81),
        ('Mabel', 'Stark', 'Mabel_Stark@birdseyeentertainment.com', 'Birdseye Entertainment', 22, 'Engineering Manager', '2013-11-27', 1, 'starkma', null, 82),
        ('Cristopher', 'Conrad', 'Cristopher_Conrad@birdseyeentertainment.com', 'Birdseye Entertainment', 49, 'Engineering Manager', '2018-01-18', 1, 'conradcr', null, 83),
        ('Kip', 'Sims', 'Kip_Sims@birdseyeentertainment.com', 'Birdseye Entertainment', 40, 'Engineering Manager', '2014-07-25', 1, 'simski', null, 84),
        ('Ronald', 'Paul', 'Ronald_Paul@birdseyeentertainment.com', 'Birdseye Entertainment', 32, 'Engineering Manager', '2000-07-12', 1, 'paulro', null, 85),
        ('Josie', 'Mcmillan', 'Josie_Mcmillan@birdseyeentertainment.com', 'Birdseye Entertainment', 64, 'Engineering Manager', '2003-10-11', 1, 'mcmillanjo', null, 86),
        ('Chang', 'Velez', 'Chang_Velez@birdseyeentertainment.com', 'Birdseye Entertainment', 30, 'Engineering Manager', '2000-03-12', 1, 'velezch', null, 87),
        ('Laura', 'Macdonald', 'Laura_Macdonald@birdseyeentertainment.com', 'Birdseye Entertainment', 59, 'Engineering Manager', '2009-06-01', 1, 'macdonaldla', null, 88),
        ('Willian', 'Hawkins', 'Willian_Hawkins@birdseyeentertainment.com', 'Birdseye Entertainment', 8, 'Engineering Manager', '2005-10-11', 1, 'hawkinswi', null, 89),
        ('Luciano', 'Doyle', 'Luciano_Doyle@birdseyeentertainment.com', 'Birdseye Entertainment', 61, 'Engineering Manager', '2017-08-01', 1, 'doylelu', null, 90),
        ('Johanna', 'Herman', 'Johanna_Herman@birdseyeentertainment.com', 'Birdseye Entertainment', 71, 'Engineering Manager', '2014-08-12', 1, 'hermanjo', null, 91),
        ('Stefan', 'Calhoun', 'Stefan_Calhoun@birdseyeentertainment.com', 'Birdseye Entertainment', 9, 'Engineering Manager', '2008-11-23', 1, 'calhounst', null, 92),
        ('Lizzie', 'Glover', 'Lizzie_Glover@birdseyeentertainment.com', 'Birdseye Entertainment', 85, 'Engineering Manager', '2007-08-20', 1, 'gloverli', null, 93),
        ('Luann', 'Ward', 'Luann_Ward@birdseyeentertainment.com', 'Birdseye Entertainment', 91, 'Engineering Manager', '2015-05-10', 1, 'wardlu', null, 94),
        ('Wesley', 'Singleton', 'Wesley_Singleton@birdseyeentertainment.com', 'Birdseye Entertainment', 19, 'Engineering Manager', '1993-01-22', 1, 'singletonwe', null, 95),
        ('Lynwood', 'Howe', 'Lynwood_Howe@birdseyeentertainment.com', 'Birdseye Entertainment', 30, 'Engineering Manager', '2000-10-02', 1, 'howely', null, 96),
        ('Lillian', 'Ali', 'Lillian_Ali@birdseyeentertainment.com', 'Birdseye Entertainment', 3, 'Engineering Manager', '2007-03-07', 1, 'alili', null, 97),
        ('Jeff', 'Maldonado', 'Jeff_Maldonado@birdseyeentertainment.com', 'Birdseye Entertainment', 54, 'Engineering Manager', '1995-06-29', 1, 'maldonadoje', null, 98),
        ('Florine', 'Barnett', 'Florine_Barnett@birdseyeentertainment.com', 'Birdseye Entertainment', 66, 'Engineering Manager', '2003-09-13', 1, 'barnettfl', null, 99),
        ('Florentino', 'Burnett', 'Florentino_Burnett@birdseyeentertainment.com', 'Birdseye Entertainment', 41, 'Engineering Manager', '1998-09-26', 1, 'burnettfl', null, 100),
        ('Ladonna', 'Peters', 'Ladonna_Peters@birdseyeentertainment.com', 'Birdseye Entertainment', 89, 'Engineering Manager', '2014-10-05', 1, 'petersla', null, 101),
        ('Giovanni', 'Francis', 'Giovanni_Francis@birdseyeentertainment.com', 'Birdseye Entertainment', 94, 'Engineering Manager', '1995-05-27', 1, 'francisgi', null, 102),
        ('Maryann', 'Roach', 'Maryann_Roach@birdseyeentertainment.com', 'Birdseye Entertainment', 102, 'Engineering Manager', '1994-12-29', 1, 'roachma', null, 103),
        ('Kurt', 'Mann', 'Kurt_Mann@birdseyeentertainment.com', 'Birdseye Entertainment', 80, 'Engineering Manager', '1999-05-25', 1, 'mannku', null, 104),
        ('Carroll', 'Austin', 'Carroll_Austin@birdseyeentertainment.com', 'Birdseye Entertainment', 37, 'Engineering Manager', '1998-07-10', 1, 'austinca', null, 105),
        ('Rosemarie', 'Rivas', 'Rosemarie_Rivas@birdseyeentertainment.com', 'Birdseye Entertainment', 44, 'Engineering Manager', '2010-09-22', 1, 'rivasro', null, 106),
        ('Faustino', 'Hodge', 'Faustino_Hodge@birdseyeentertainment.com', 'Birdseye Entertainment', 47, 'Engineering Manager', '2014-05-30', 1, 'hodgefa', null, 107),
        ('Dallas', 'Yates', 'Dallas_Yates@birdseyeentertainment.com', 'Birdseye Entertainment', 53, 'Engineering Manager', '2015-03-07', 1, 'yatesda', null, 108),
        ('Tania', 'Valencia', 'Tania_Valencia@birdseyeentertainment.com', 'Birdseye Entertainment', 79, 'Engineering Manager', '2014-09-20', 1, 'valenciata', null, 109),
        ('Kelly', 'Higgins', 'Kelly_Higgins@birdseyeentertainment.com', 'Birdseye Entertainment', 100, 'Engineering Manager', '2003-01-26', 1, 'higginske', null, 110),
        ('Harlan', 'Brown', 'Harlan_Brown@birdseyeentertainment.com', 'Birdseye Entertainment', 46, 'Engineering Manager', '2003-10-13', 1, 'brownha', null, 111),
        ('Shawn', 'Fowler', 'Shawn_Fowler@birdseyeentertainment.com', 'Birdseye Entertainment', 32, 'Engineering Manager', '2002-06-06', 1, 'fowlersh', null, 112),
        ('Miriam', 'Wilkinson', 'Miriam_Wilkinson@birdseyeentertainment.com', 'Birdseye Entertainment', 85, 'Engineering Manager', '2007-02-14', 1, 'wilkinsonmi', null, 113),
        ('Wendi', 'Perry', 'Wendi_Perry@birdseyeentertainment.com', 'Birdseye Entertainment', 55, 'Engineering Manager', '2005-11-15', 1, 'perrywe', null, 114),
        ('Reyna', 'Lutz', 'Reyna_Lutz@birdseyeentertainment.com', 'Birdseye Entertainment', 114, 'Engineering Manager', '2012-12-01', 1, 'lutzre', null, 115),
        ('Forest', 'Bailey', 'Forest_Bailey@birdseyeentertainment.com', 'Birdseye Entertainment', 28, 'Engineering Manager', '2003-09-10', 1, 'baileyfo', null, 116),
        ('Jeremiah', 'Davis', 'Jeremiah_Davis@birdseyeentertainment.com', 'Birdseye Entertainment', 40, 'Engineering Manager', '1997-09-13', 1, 'davisje', null, 117),
        ('Imogene', 'Rivas', 'Imogene_Rivas@birdseyeentertainment.com', 'Birdseye Entertainment', 50, 'Engineering Manager', '2017-03-05', 1, 'rivasim', null, 118),
        ('Lauri', 'Valencia', 'Lauri_Valencia@birdseyeentertainment.com', 'Birdseye Entertainment', 17, 'Engineering Manager', '1995-11-01', 1, 'valenciala', null, 119),
        ('Kathryn', 'Nelson', 'Kathryn_Nelson@birdseyeentertainment.com', 'Birdseye Entertainment', 49, 'Engineering Manager', '1994-11-27', 1, 'nelsonka', null, 120),
        ('Bennett', 'West', 'Bennett_West@birdseyeentertainment.com', 'Birdseye Entertainment', 22, 'Engineering Manager', '2012-02-02', 1, 'westbe', null, 121),
        ('Rafael', 'Arroyo', 'Rafael_Arroyo@birdseyeentertainment.com', 'Birdseye Entertainment', 65, 'Engineering Manager', '2005-06-04', 1, 'arroyora', null, 122),
        ('Marvin', 'Goodman', 'Marvin_Goodman@birdseyeentertainment.com', 'Birdseye Entertainment', 50, 'Engineering Manager', '1997-10-20', 1, 'goodmanma', null, 123),
        ('Raquel', 'Grimes', 'Raquel_Grimes@birdseyeentertainment.com', 'Birdseye Entertainment', 84, 'Engineering Manager', '1993-11-26', 1, 'grimesra', null, 124),
        ('Rena', 'Ruiz', 'Rena_Ruiz@birdseyeentertainment.com', 'Birdseye Entertainment', 61, 'Engineering Manager', '2003-05-20', 1, 'ruizre', null, 125),
        ('Isidro', 'Compton', 'Isidro_Compton@birdseyeentertainment.com', 'Birdseye Entertainment', 46, 'Engineering Manager', '1999-06-04', 1, 'comptonis', null, 126),
        ('Woodrow', 'Simpson', 'Woodrow_Simpson@birdseyeentertainment.com', 'Birdseye Entertainment', 37, 'Engineering Manager', '1998-03-27', 1, 'simpsonwo', null, 127),
        ('Aida', 'Hancock', 'Aida_Hancock@birdseyeentertainment.com', 'Birdseye Entertainment', 73, 'Engineering Manager', '1993-11-09', 1, 'hancockai', null, 128),
        ('Kenneth', 'Byrd', 'Kenneth_Byrd@birdseyeentertainment.com', 'Birdseye Entertainment', 116, 'Engineering Manager', '1996-12-10', 1, 'byrdke', null, 129),
        ('Luigi', 'Rhodes', 'Luigi_Rhodes@birdseyeentertainment.com', 'Birdseye Entertainment', 59, 'Engineering Manager', '2002-04-13', 1, 'rhodeslu', null, 130),
        ('Danial', 'Villa', 'Danial_Villa@birdseyeentertainment.com', 'Birdseye Entertainment', 24, 'Engineering Manager', '2017-12-25', 1, 'villada', null, 131),
        ('Harold', 'Diaz', 'Harold_Diaz@birdseyeentertainment.com', 'Birdseye Entertainment', 80, 'Engineering Manager', '1991-02-23', 1, 'diazha', null, 132),
        ('Virgie', 'Green', 'Virgie_Green@birdseyeentertainment.com', 'Birdseye Entertainment', 49, 'Engineering Manager', '1990-01-08', 1, 'greenvi', null, 133),
        ('Tania', 'Stout', 'Tania_Stout@birdseyeentertainment.com', 'Birdseye Entertainment', 13, 'Engineering Manager', '2001-06-03', 1, 'stoutta', null, 134),
        ('Jasmine', 'Melendez', 'Jasmine_Melendez@birdseyeentertainment.com', 'Birdseye Entertainment', 15, 'Engineering Manager', '2006-02-05', 1, 'melendezja', null, 135),
        ('Enid', 'Andersen', 'Enid_Andersen@birdseyeentertainment.com', 'Birdseye Entertainment', 8, 'Engineering Manager', '1995-12-24', 1, 'andersenen', null, 136),
        ('Ashley', 'Mckinney', 'Ashley_Mckinney@birdseyeentertainment.com', 'Birdseye Entertainment', 100, 'Engineering Manager', '1996-09-18', 1, 'mckinneyas', null, 137),
        ('Bernard', 'Ware', 'Bernard_Ware@birdseyeentertainment.com', 'Birdseye Entertainment', 4, 'Engineering Manager', '2009-08-27', 1, 'warebe', null, 138),
        ('Bessie', 'Richmond', 'Bessie_Richmond@birdseyeentertainment.com', 'Birdseye Entertainment', 14, 'Engineering Manager', '2013-01-12', 1, 'richmondbe', null, 139),
        ('Gail', 'Lindsey', 'Gail_Lindsey@birdseyeentertainment.com', 'Birdseye Entertainment', 87, 'Engineering Manager', '2010-09-15', 1, 'lindseyga', null, 140),
        ('Filiberto', 'Maynard', 'Filiberto_Maynard@birdseyeentertainment.com', 'Birdseye Entertainment', 6, 'Engineering Manager', '2011-03-25', 1, 'maynardfi', null, 141),
        ('Ellen', 'Vaughan', 'Ellen_Vaughan@birdseyeentertainment.com', 'Birdseye Entertainment', 26, 'Engineering Manager', '1990-04-23', 1, 'vaughanel', null, 142),
        ('Logan', 'Yates', 'Logan_Yates@birdseyeentertainment.com', 'Birdseye Entertainment', 21, 'Engineering Manager', '2009-04-12', 1, 'yateslo', null, 143),
        ('Randy', 'Velez', 'Randy_Velez@birdseyeentertainment.com', 'Birdseye Entertainment', 64, 'Engineering Manager', '2005-04-21', 1, 'velezra', null, 144),
        ('Kareem', 'Grant', 'Kareem_Grant@birdseyeentertainment.com', 'Birdseye Entertainment', 86, 'Engineering Manager', '1993-06-21', 1, 'grantka', null, 145),
        ('Thomas', 'Ryan', 'Thomas_Ryan@birdseyeentertainment.com', 'Birdseye Entertainment', 140, 'Engineering Manager', '2012-02-16', 1, 'ryanth', null, 146),
        ('Polly', 'Cherry', 'Polly_Cherry@birdseyeentertainment.com', 'Birdseye Entertainment', 99, 'Engineering Manager', '1995-07-26', 1, 'cherrypo', null, 147),
        ('Mark', 'Barrera', 'Mark_Barrera@birdseyeentertainment.com', 'Birdseye Entertainment', 95, 'Engineering Manager', '1991-12-04', 1, 'barrerama', null, 148),
        ('Micah', 'Pace', 'Micah_Pace@birdseyeentertainment.com', 'Birdseye Entertainment', 121, 'Engineering Manager', '2011-12-10', 1, 'pacemi', null, 149),
        ('Jasper', 'Cannon', 'Jasper_Cannon@birdseyeentertainment.com', 'Birdseye Entertainment', 59, 'Engineering Manager', '2008-04-25', 1, 'cannonja', null, 150),
        ('Isaias', 'Watson', 'Isaias_Watson@birdseyeentertainment.com', 'Birdseye Entertainment', 115, 'Engineering Manager', '2012-10-06', 1, 'watsonis', null, 151),
        ('Leigh', 'Burnett', 'Leigh_Burnett@birdseyeentertainment.com', 'Birdseye Entertainment', 134, 'Engineering Manager', '2014-01-01', 1, 'burnettle', null, 152),
        ('Kory', 'Sheppard', 'Kory_Sheppard@birdseyeentertainment.com', 'Birdseye Entertainment', 108, 'Engineering Manager', '2004-09-27', 1, 'sheppardko', null, 153),
        ('Berry', 'Barber', 'Berry_Barber@birdseyeentertainment.com', 'Birdseye Entertainment', 131, 'Engineering Manager', '2008-02-03', 1, 'barberbe', null, 154),
        ('Brenda', 'Clarke', 'Brenda_Clarke@birdseyeentertainment.com', 'Birdseye Entertainment', 120, 'Engineering Manager', '2005-04-13', 1, 'clarkebr', null, 155),
        ('Gabriel', 'Bruce', 'Gabriel_Bruce@birdseyeentertainment.com', 'Birdseye Entertainment', 118, 'Engineering Manager', '1995-04-02', 1, 'brucega', null, 156),
        ('Wilton', 'Duncan', 'Wilton_Duncan@birdseyeentertainment.com', 'Birdseye Entertainment', 73, 'Engineering Manager', '2006-05-07', 1, 'duncanwi', null, 157),
        ('Horace', 'Drake', 'Horace_Drake@birdseyeentertainment.com', 'Birdseye Entertainment', 99, 'Engineering Manager', '2004-04-22', 1, 'drakeho', null, 158),
        ('Krista', 'Mata', 'Krista_Mata@birdseyeentertainment.com', 'Birdseye Entertainment', 50, 'Engineering Manager', '2012-01-14', 1, 'matakr', null, 159),
        ('Angelita', 'Moyer', 'Angelita_Moyer@birdseyeentertainment.com', 'Birdseye Entertainment', 6, 'Engineering Manager', '1990-01-31', 1, 'moyeran', null, 160),
        ('Bridgette', 'Cardenas', 'Bridgette_Cardenas@birdseyeentertainment.com', 'Birdseye Entertainment', 146, 'Engineering Manager', '2006-04-11', 1, 'cardenasbr', null, 161),
        ('Lorie', 'Fletcher', 'Lorie_Fletcher@birdseyeentertainment.com', 'Birdseye Entertainment', 115, 'Engineering Manager', '1992-07-09', 1, 'fletcherlo', null, 162),
        ('Bryce', 'Hicks', 'Bryce_Hicks@birdseyeentertainment.com', 'Birdseye Entertainment', 66, 'Engineering Manager', '1992-10-11', 1, 'hicksbr', null, 163),
        ('Clare', 'Boyd', 'Clare_Boyd@birdseyeentertainment.com', 'Birdseye Entertainment', 127, 'Engineering Manager', '1996-03-29', 1, 'boydcl', null, 164),
        ('Jenny', 'Lara', 'Jenny_Lara@birdseyeentertainment.com', 'Birdseye Entertainment', 105, 'Engineering Manager', '2015-11-22', 1, 'laraje', null, 165),
        ('Carlene', 'Ponce', 'Carlene_Ponce@birdseyeentertainment.com', 'Birdseye Entertainment', 70, 'Engineering Manager', '2001-01-19', 1, 'ponceca', null, 166),
        ('Mckinley', 'Ali', 'Mckinley_Ali@birdseyeentertainment.com', 'Birdseye Entertainment', 95, 'Engineering Manager', '2011-01-27', 1, 'alimc', null, 167),
        ('Bonnie', 'Arroyo', 'Bonnie_Arroyo@birdseyeentertainment.com', 'Birdseye Entertainment', 92, 'Software Engineer I', '2009-08-24', 0, 'arroyobo', null, 168),
        ('Rosie', 'Banks', 'Rosie_Banks@birdseyeentertainment.com', 'Birdseye Entertainment', 28, 'DevOps Engineer', '1996-03-22', 0, 'banksro', null, 169),
        ('Bertie', 'Howell', 'Bertie_Howell@birdseyeentertainment.com', 'Birdseye Entertainment', 135, 'Software Architect', '1996-01-05', 0, 'howellbe', null, 170),
        ('Sherri', 'Weiss', 'Sherri_Weiss@birdseyeentertainment.com', 'Birdseye Entertainment', 28, 'Site Reliability Engineer', '1997-06-13', 0, 'weisssh', null, 171),
        ('Alfreda', 'Wright', 'Alfreda_Wright@birdseyeentertainment.com', 'Birdseye Entertainment', 66, 'Site Reliability Engineer', '1990-07-21', 0, 'wrightal', null, 172),
        ('Carmella', 'Juarez', 'Carmella_Juarez@birdseyeentertainment.com', 'Birdseye Entertainment', 147, 'Principal Software Architect', '1995-12-04', 0, 'juarezca', null, 173),
        ('Jerrod', 'Mccarty', 'Jerrod_Mccarty@birdseyeentertainment.com', 'Birdseye Entertainment', 156, 'Tech Lead', '2010-03-07', 0, 'mccartyje', null, 174),
        ('Sung', 'Woodard', 'Sung_Woodard@birdseyeentertainment.com', 'Birdseye Entertainment', 158, 'Software Engineer II', '1993-05-06', 0, 'woodardsu', null, 175),
        ('Darron', 'Mack', 'Darron_Mack@birdseyeentertainment.com', 'Birdseye Entertainment', 87, 'DevOps Engineer', '2018-12-05', 0, 'mackda', null, 176),
        ('Ron', 'Sellers', 'Ron_Sellers@birdseyeentertainment.com', 'Birdseye Entertainment', 49, 'Software Architect', '2016-08-04', 0, 'sellersro', null, 177),
        ('Tracy', 'Flores', 'Tracy_Flores@birdseyeentertainment.com', 'Birdseye Entertainment', 42, 'Site Reliability Engineer', '2011-09-12', 0, 'florestr', null, 178),
        ('Janine', 'Day', 'Janine_Day@birdseyeentertainment.com', 'Birdseye Entertainment', 3, 'Principal Software Architect', '1999-03-13', 0, 'dayja', null, 179),
        ('Jamaal', 'Campbell', 'Jamaal_Campbell@birdseyeentertainment.com', 'Birdseye Entertainment', 30, 'Software Architect', '2018-07-14', 0, 'campbellja', null, 180),
        ('Dona', 'Sloan', 'Dona_Sloan@birdseyeentertainment.com', 'Birdseye Entertainment', 67, 'DevOps Engineer', '1992-02-24', 0, 'sloando', null, 181),
        ('Rachel', 'Gilbert', 'Rachel_Gilbert@birdseyeentertainment.com', 'Birdseye Entertainment', 130, 'Site Reliability Engineer', '1992-07-01', 0, 'gilbertra', null, 182),
        ('Jamal', 'Morrow', 'Jamal_Morrow@birdseyeentertainment.com', 'Birdseye Entertainment', 35, 'Principal Software Architect', '2001-01-05', 0, 'morrowja', null, 183),
        ('Kaye', 'Dennis', 'Kaye_Dennis@birdseyeentertainment.com', 'Birdseye Entertainment', 138, 'Software Architect', '2012-12-08', 0, 'denniska', null, 184),
        ('Tomas', 'Fritz', 'Tomas_Fritz@birdseyeentertainment.com', 'Birdseye Entertainment', 101, 'Senior Software Engineer', '1995-07-21', 0, 'fritzto', null, 185),
        ('Shirley', 'Cooley', 'Shirley_Cooley@birdseyeentertainment.com', 'Birdseye Entertainment', 60, 'Software Engineer II', '2008-10-29', 0, 'cooleysh', null, 186),
        ('Marisa', 'Henderson', 'Marisa_Henderson@birdseyeentertainment.com', 'Birdseye Entertainment', 47, 'Software Engineer II', '2003-11-20', 0, 'hendersonma', null, 187),
        ('Joy', 'Vaughn', 'Joy_Vaughn@birdseyeentertainment.com', 'Birdseye Entertainment', 61, 'Tech Lead', '2010-06-14', 0, 'vaughnjo', null, 188),
        ('Melva', 'Jones', 'Melva_Jones@birdseyeentertainment.com', 'Birdseye Entertainment', 101, 'DevOps Engineer', '2002-11-07', 0, 'jonesme', null, 189),
        ('Stella', 'Chambers', 'Stella_Chambers@birdseyeentertainment.com', 'Birdseye Entertainment', 76, 'Tech Lead', '2018-09-26', 0, 'chambersst', null, 190),
        ('Dante', 'Coleman', 'Dante_Coleman@birdseyeentertainment.com', 'Birdseye Entertainment', 65, 'Principal Software Architect', '1998-04-14', 0, 'colemanda', null, 191),
        ('Whitney', 'Fitzpatrick', 'Whitney_Fitzpatrick@birdseyeentertainment.com', 'Birdseye Entertainment', 141, 'Site Reliability Engineer', '2010-08-07', 0, 'fitzpatrickwh', null, 192),
        ('Raul', 'Rowland', 'Raul_Rowland@birdseyeentertainment.com', 'Birdseye Entertainment', 166, 'Software Engineer II', '2014-11-18', 0, 'rowlandra', null, 193),
        ('Curtis', 'Bean', 'Curtis_Bean@birdseyeentertainment.com', 'Birdseye Entertainment', 44, 'Site Reliability Engineer', '1999-06-26', 0, 'beancu', null, 194),
        ('Latasha', 'Bray', 'Latasha_Bray@birdseyeentertainment.com', 'Birdseye Entertainment', 5, 'Senior Software Engineer', '2016-03-06', 0, 'brayla', null, 195),
        ('Otto', 'Finley', 'Otto_Finley@birdseyeentertainment.com', 'Birdseye Entertainment', 13, 'DevOps Engineer', '1999-11-07', 0, 'finleyot', null, 196),
        ('Von', 'Fernandez', 'Von_Fernandez@birdseyeentertainment.com', 'Birdseye Entertainment', 12, 'Site Reliability Engineer', '1994-03-05', 0, 'fernandezvo', null, 197),
        ('Paula', 'Schroeder', 'Paula_Schroeder@birdseyeentertainment.com', 'Birdseye Entertainment', 27, 'Software Architect', '1997-04-25', 0, 'schroederpa', null, 198),
        ('Aileen', 'Torres', 'Aileen_Torres@birdseyeentertainment.com', 'Birdseye Entertainment', 42, 'DevOps Engineer', '2005-06-11', 0, 'torresai', null, 199),
        ('Jimmy', 'Sanchez', 'Jimmy_Sanchez@birdseyeentertainment.com', 'Birdseye Entertainment', 132, 'Principal Software Architect', '1990-05-06', 0, 'sanchezji', null, 200),
        ('Janis', 'Horton', 'Janis_Horton@birdseyeentertainment.com', 'Birdseye Entertainment', 160, 'Senior Software Engineer', '2018-12-02', 0, 'hortonja', null, 201),
        ('Eugenia', 'Olson', 'Eugenia_Olson@birdseyeentertainment.com', 'Birdseye Entertainment', 150, 'Tech Lead', '1995-10-26', 0, 'olsoneu', null, 202),
        ('Hipolito', 'Jenkins', 'Hipolito_Jenkins@birdseyeentertainment.com', 'Birdseye Entertainment', 122, 'Site Reliability Engineer', '2008-12-28', 0, 'jenkinshi', null, 203),
        ('Alexis', 'Ware', 'Alexis_Ware@birdseyeentertainment.com', 'Birdseye Entertainment', 164, 'Senior Software Engineer', '1997-11-03', 0, 'wareal', null, 204),
        ('Gladys', 'Petersen', 'Gladys_Petersen@birdseyeentertainment.com', 'Birdseye Entertainment', 38, 'Site Reliability Engineer', '2017-08-18', 0, 'petersengl', null, 205),
        ('Chang', 'Schmidt', 'Chang_Schmidt@birdseyeentertainment.com', 'Birdseye Entertainment', 52, 'Site Reliability Engineer', '2018-10-04', 0, 'schmidtch', null, 206),
        ('Mallory', 'Pruitt', 'Mallory_Pruitt@birdseyeentertainment.com', 'Birdseye Entertainment', 111, 'Principal Software Architect', '2000-05-20', 0, 'pruittma', null, 207),
        ('Juliette', 'Downs', 'Juliette_Downs@birdseyeentertainment.com', 'Birdseye Entertainment', 74, 'Principal Software Architect', '1994-03-31', 0, 'downsju', null, 208),
        ('Erick', 'Camacho', 'Erick_Camacho@birdseyeentertainment.com', 'Birdseye Entertainment', 37, 'Site Reliability Engineer', '2007-02-11', 0, 'camachoer', null, 209),
        ('Lydia', 'Fisher', 'Lydia_Fisher@birdseyeentertainment.com', 'Birdseye Entertainment', 84, 'Tech Lead', '2001-06-21', 0, 'fisherly', null, 210),
        ('Willie', 'Harmon', 'Willie_Harmon@birdseyeentertainment.com', 'Birdseye Entertainment', 111, 'Software Architect', '2005-12-09', 0, 'harmonwi', null, 211),
        ('Evan', 'Stewart', 'Evan_Stewart@birdseyeentertainment.com', 'Birdseye Entertainment', 33, 'Senior Software Engineer', '2018-09-15', 0, 'stewartev', null, 212),
        ('Abdul', 'Calhoun', 'Abdul_Calhoun@birdseyeentertainment.com', 'Birdseye Entertainment', 94, 'Principal Software Architect', '1999-07-15', 0, 'calhounab', null, 213),
        ('Dwayne', 'Mckee', 'Dwayne_Mckee@birdseyeentertainment.com', 'Birdseye Entertainment', 26, 'Site Reliability Engineer', '2014-03-03', 0, 'mckeedw', null, 214),
        ('Clarissa', 'Rivas', 'Clarissa_Rivas@birdseyeentertainment.com', 'Birdseye Entertainment', 108, 'Software Engineer II', '2000-08-28', 0, 'rivascl', null, 215),
        ('Cara', 'Wiggins', 'Cara_Wiggins@birdseyeentertainment.com', 'Birdseye Entertainment', 158, 'DevOps Engineer', '2001-07-23', 0, 'wigginsca', null, 216),
        ('Kip', 'Barr', 'Kip_Barr@birdseyeentertainment.com', 'Birdseye Entertainment', 40, 'Tech Lead', '1992-08-07', 0, 'barrki', null, 217),
        ('Stanton', 'Schwartz', 'Stanton_Schwartz@birdseyeentertainment.com', 'Birdseye Entertainment', 66, 'Software Architect', '2010-05-24', 0, 'schwartzst', null, 218),
        ('Tina', 'Haney', 'Tina_Haney@birdseyeentertainment.com', 'Birdseye Entertainment', 43, 'Principal Software Architect', '2000-06-04', 0, 'haneyti', null, 219),
        ('Angel', 'Gray', 'Angel_Gray@birdseyeentertainment.com', 'Birdseye Entertainment', 128, 'Tech Lead', '1995-11-17', 0, 'grayan', null, 220),
        ('Dane', 'Baldwin', 'Dane_Baldwin@birdseyeentertainment.com', 'Birdseye Entertainment', 124, 'Senior Software Engineer', '2014-05-22', 0, 'baldwinda', null, 221),
        ('Daron', 'Melendez', 'Daron_Melendez@birdseyeentertainment.com', 'Birdseye Entertainment', 7, 'DevOps Engineer', '2010-12-18', 0, 'melendezda', null, 222),
        ('Roxanne', 'Butler', 'Roxanne_Butler@birdseyeentertainment.com', 'Birdseye Entertainment', 114, 'Tech Lead', '1995-05-05', 0, 'butlerro', null, 223),
        ('Cliff', 'Rubio', 'Cliff_Rubio@birdseyeentertainment.com', 'Birdseye Entertainment', 139, 'Tech Lead', '1996-01-08', 0, 'rubiocl', null, 224),
        ('Terrence', 'Mckee', 'Terrence_Mckee@birdseyeentertainment.com', 'Birdseye Entertainment', 165, 'Tech Lead', '2009-02-07', 0, 'mckeete', null, 225),
        ('Stevie', 'Crane', 'Stevie_Crane@birdseyeentertainment.com', 'Birdseye Entertainment', 55, 'Software Architect', '2005-12-25', 0, 'cranest', null, 226),
        ('Reuben', 'Simmons', 'Reuben_Simmons@birdseyeentertainment.com', 'Birdseye Entertainment', 17, 'Senior Software Engineer', '1995-07-29', 0, 'simmonsre', null, 227),
        ('Luigi', 'Hayes', 'Luigi_Hayes@birdseyeentertainment.com', 'Birdseye Entertainment', 113, 'Software Engineer II', '1995-08-29', 0, 'hayeslu', null, 228),
        ('Gerardo', 'Carter', 'Gerardo_Carter@birdseyeentertainment.com', 'Birdseye Entertainment', 143, 'Tech Lead', '2007-01-13', 0, 'carterge', null, 229),
        ('Staci', 'Delgado', 'Staci_Delgado@birdseyeentertainment.com', 'Birdseye Entertainment', 72, 'Software Engineer II', '2009-07-09', 0, 'delgadost', null, 230),
        ('Jaime', 'Solomon', 'Jaime_Solomon@birdseyeentertainment.com', 'Birdseye Entertainment', 23, 'Principal Software Architect', '2000-06-09', 0, 'solomonja', null, 231),
        ('Joe', 'Williamson', 'Joe_Williamson@birdseyeentertainment.com', 'Birdseye Entertainment', 39, 'Software Engineer II', '2015-09-26', 0, 'williamsonjo', null, 232),
        ('Brett', 'Krueger', 'Brett_Krueger@birdseyeentertainment.com', 'Birdseye Entertainment', 2, 'Software Engineer II', '2017-09-03', 0, 'kruegerbr', null, 233),
        ('Angel', 'Skinner', 'Angel_Skinner@birdseyeentertainment.com', 'Birdseye Entertainment', 94, 'Principal Software Architect', '2012-02-27', 0, 'skinneran', null, 234),
        ('Kirsten', 'Melton', 'Kirsten_Melton@birdseyeentertainment.com', 'Birdseye Entertainment', 40, 'Senior Software Engineer', '2005-04-27', 0, 'meltonki', null, 235),
        ('Jan', 'Gray', 'Jan_Gray@birdseyeentertainment.com', 'Birdseye Entertainment', 80, 'DevOps Engineer', '1995-12-23', 0, 'grayja', null, 236),
        ('Michale', 'Briggs', 'Michale_Briggs@birdseyeentertainment.com', 'Birdseye Entertainment', 105, 'Site Reliability Engineer', '2009-09-30', 0, 'briggsmi', null, 237),
        ('Garland', 'Pacheco', 'Garland_Pacheco@birdseyeentertainment.com', 'Birdseye Entertainment', 91, 'Software Architect', '2010-10-23', 0, 'pachecoga', null, 238),
        ('Andrea', 'Cooley', 'Andrea_Cooley@birdseyeentertainment.com', 'Birdseye Entertainment', 9, 'Senior Software Engineer', '2008-03-14', 0, 'cooleyan', null, 239),
        ('Dillon', 'Rodgers', 'Dillon_Rodgers@birdseyeentertainment.com', 'Birdseye Entertainment', 126, 'DevOps Engineer', '1992-03-11', 0, 'rodgersdi', null, 240),
        ('George', 'Garcia', 'George_Garcia@birdseyeentertainment.com', 'Birdseye Entertainment', 21, 'Site Reliability Engineer', '2005-04-30', 0, 'garciage', null, 241),
        ('Forrest', 'Ali', 'Forrest_Ali@birdseyeentertainment.com', 'Birdseye Entertainment', 28, 'Software Architect', '2008-09-26', 0, 'alifo', null, 242),
        ('Herminia', 'Novak', 'Herminia_Novak@birdseyeentertainment.com', 'Birdseye Entertainment', 89, 'Senior Software Engineer', '1996-01-12', 0, 'novakhe', null, 243),
        ('Leigh', 'Trujillo', 'Leigh_Trujillo@birdseyeentertainment.com', 'Birdseye Entertainment', 21, 'Tech Lead', '2009-02-07', 0, 'trujillole', null, 244),
        ('Mara', 'Haley', 'Mara_Haley@birdseyeentertainment.com', 'Birdseye Entertainment', 113, 'Software Engineer II', '1993-07-22', 0, 'haleyma', null, 245),
        ('Mohamed', 'Coffey', 'Mohamed_Coffey@birdseyeentertainment.com', 'Birdseye Entertainment', 28, 'Site Reliability Engineer', '1994-10-06', 0, 'coffeymo', null, 246),
        ('Bradford', 'Carroll', 'Bradford_Carroll@birdseyeentertainment.com', 'Birdseye Entertainment', 49, 'Tech Lead', '2011-12-15', 0, 'carrollbr', null, 247),
        ('Burl', 'Mora', 'Burl_Mora@birdseyeentertainment.com', 'Birdseye Entertainment', 153, 'Site Reliability Engineer', '1994-01-21', 0, 'morabu', null, 248),
        ('Broderick', 'Tucker', 'Broderick_Tucker@birdseyeentertainment.com', 'Birdseye Entertainment', 154, 'Software Engineer II', '1996-09-07', 0, 'tuckerbr', null, 249),
        ('Keven', 'Dougherty', 'Keven_Dougherty@birdseyeentertainment.com', 'Birdseye Entertainment', 47, 'Tech Lead', '2016-06-01', 0, 'doughertyke', null, 250),
        ('Glenda', 'Dodson', 'Glenda_Dodson@birdseyeentertainment.com', 'Birdseye Entertainment', 162, 'Principal Software Architect', '1997-01-13', 0, 'dodsongl', null, 251),
        ('Alton', 'Frost', 'Alton_Frost@birdseyeentertainment.com', 'Birdseye Entertainment', 118, 'Software Engineer II', '2012-02-28', 0, 'frostal', null, 252),
        ('Claudio', 'Richards', 'Claudio_Richards@birdseyeentertainment.com', 'Birdseye Entertainment', 105, 'Site Reliability Engineer', '1993-11-12', 0, 'richardscl', null, 253),
        ('Elton', 'Ortiz', 'Elton_Ortiz@birdseyeentertainment.com', 'Birdseye Entertainment', 22, 'Site Reliability Engineer', '1996-07-19', 0, 'ortizel', null, 254),
        ('Lottie', 'Willis', 'Lottie_Willis@birdseyeentertainment.com', 'Birdseye Entertainment', 55, 'Software Engineer II', '1999-02-02', 0, 'willislo', null, 255),
        ('Priscilla', 'Barry', 'Priscilla_Barry@birdseyeentertainment.com', 'Birdseye Entertainment', 80, 'Software Engineer II', '1997-02-21', 0, 'barrypr', null, 256),
        ('Mary', 'Matthews', 'Mary_Matthews@birdseyeentertainment.com', 'Birdseye Entertainment', 106, 'Principal Software Architect', '2003-01-27', 0, 'matthewsma', null, 257),
        ('Amy', 'Randall', 'Amy_Randall@birdseyeentertainment.com', 'Birdseye Entertainment', 105, 'Site Reliability Engineer', '1999-11-19', 0, 'randallam', null, 258),
        ('Young', 'Good', 'Young_Good@birdseyeentertainment.com', 'Birdseye Entertainment', 60, 'Software Engineer II', '2009-10-14', 0, 'goodyo', null, 259),
        ('Pearl', 'Olsen', 'Pearl_Olsen@birdseyeentertainment.com', 'Birdseye Entertainment', 153, 'DevOps Engineer', '1992-11-20', 0, 'olsenpe', null, 260),
        ('Malcom', 'Valencia', 'Malcom_Valencia@birdseyeentertainment.com', 'Birdseye Entertainment', 124, 'Senior Software Engineer', '2000-03-01', 0, 'valenciama', null, 261),
        ('Garrett', 'Wilkinson', 'Garrett_Wilkinson@birdseyeentertainment.com', 'Birdseye Entertainment', 34, 'Software Engineer II', '2017-01-20', 0, 'wilkinsonga', null, 262),
        ('Beatrice', 'Mcclain', 'Beatrice_Mcclain@birdseyeentertainment.com', 'Birdseye Entertainment', 91, 'DevOps Engineer', '2015-02-22', 0, 'mcclainbe', null, 263),
        ('Susana', 'Thornton', 'Susana_Thornton@birdseyeentertainment.com', 'Birdseye Entertainment', 131, 'Software Engineer II', '2016-09-11', 0, 'thorntonsu', null, 264),
        ('Charmaine', 'Molina', 'Charmaine_Molina@birdseyeentertainment.com', 'Birdseye Entertainment', 128, 'Software Engineer II', '2010-12-04', 0, 'molinach', null, 265),
        ('Geraldo', 'Wilkinson', 'Geraldo_Wilkinson@birdseyeentertainment.com', 'Birdseye Entertainment', 49, 'Site Reliability Engineer', '1992-05-16', 0, 'wilkinsonge', null, 266),
        ('Hollis', 'Wilkinson', 'Hollis_Wilkinson@birdseyeentertainment.com', 'Birdseye Entertainment', 14, 'Tech Lead', '1994-02-27', 0, 'wilkinsonho', null, 267),
        ('Joan', 'Dunlap', 'Joan_Dunlap@birdseyeentertainment.com', 'Birdseye Entertainment', 52, 'DevOps Engineer', '1995-11-05', 0, 'dunlapjo', null, 268),
        ('Lessie', 'Ayers', 'Lessie_Ayers@birdseyeentertainment.com', 'Birdseye Entertainment', 31, 'Senior Software Engineer', '2006-01-04', 0, 'ayersle', null, 269),
        ('Melvin', 'Wiggins', 'Melvin_Wiggins@birdseyeentertainment.com', 'Birdseye Entertainment', 12, 'Senior Software Engineer', '2012-07-04', 0, 'wigginsme', null, 270),
        ('Jerold', 'Mcneil', 'Jerold_Mcneil@birdseyeentertainment.com', 'Birdseye Entertainment', 137, 'DevOps Engineer', '2006-09-08', 0, 'mcneilje', null, 271),
        ('Chung', 'Harper', 'Chung_Harper@birdseyeentertainment.com', 'Birdseye Entertainment', 15, 'Site Reliability Engineer', '2007-03-08', 0, 'harperch', null, 272),
        ('Natalia', 'Rojas', 'Natalia_Rojas@birdseyeentertainment.com', 'Birdseye Entertainment', 73, 'Tech Lead', '2002-11-15', 0, 'rojasna', null, 273),
        ('Sheena', 'Mcintyre', 'Sheena_Mcintyre@birdseyeentertainment.com', 'Birdseye Entertainment', 55, 'Principal Software Architect', '2000-10-11', 0, 'mcintyresh', null, 274),
        ('Luella', 'Banks', 'Luella_Banks@birdseyeentertainment.com', 'Birdseye Entertainment', 126, 'Senior Software Engineer', '2018-02-10', 0, 'bankslu', null, 275),
        ('Lon', 'Patterson', 'Lon_Patterson@birdseyeentertainment.com', 'Birdseye Entertainment', 51, 'Principal Software Architect', '2001-04-04', 0, 'pattersonlo', null, 276),
        ('Jude', 'Gentry', 'Jude_Gentry@birdseyeentertainment.com', 'Birdseye Entertainment', 115, 'Site Reliability Engineer', '2016-05-18', 0, 'gentryju', null, 277),
        ('Julio', 'Kennedy', 'Julio_Kennedy@birdseyeentertainment.com', 'Birdseye Entertainment', 84, 'Software Architect', '2009-07-24', 0, 'kennedyju', null, 278),
        ('Rolf', 'Horne', 'Rolf_Horne@birdseyeentertainment.com', 'Birdseye Entertainment', 52, 'Site Reliability Engineer', '1997-08-18', 0, 'hornero', null, 279),
        ('Dolly', 'Reid', 'Dolly_Reid@birdseyeentertainment.com', 'Birdseye Entertainment', 4, 'Site Reliability Engineer', '1999-11-14', 0, 'reiddo', null, 280),
        ('Susie', 'Mayer', 'Susie_Mayer@birdseyeentertainment.com', 'Birdseye Entertainment', 22, 'DevOps Engineer', '2018-05-30', 0, 'mayersu', null, 281),
        ('Young', 'Sanford', 'Young_Sanford@birdseyeentertainment.com', 'Birdseye Entertainment', 117, 'Senior Software Engineer', '2003-08-26', 0, 'sanfordyo', null, 282),
        ('Kelly', 'Weaver', 'Kelly_Weaver@birdseyeentertainment.com', 'Birdseye Entertainment', 151, 'Software Engineer II', '2009-10-01', 0, 'weaverke', null, 283),
        ('Diana', 'Sawyer', 'Diana_Sawyer@birdseyeentertainment.com', 'Birdseye Entertainment', 125, 'Software Engineer II', '1992-12-05', 0, 'sawyerdi', null, 284),
        ('Dorsey', 'Brown', 'Dorsey_Brown@birdseyeentertainment.com', 'Birdseye Entertainment', 27, 'Tech Lead', '2013-08-08', 0, 'browndo', null, 285),
        ('Craig', 'Eaton', 'Craig_Eaton@birdseyeentertainment.com', 'Birdseye Entertainment', 122, 'Tech Lead', '2008-02-05', 0, 'eatoncr', null, 286),
        ('Laurence', 'Swanson', 'Laurence_Swanson@birdseyeentertainment.com', 'Birdseye Entertainment', 30, 'Site Reliability Engineer', '1990-04-03', 0, 'swansonla', null, 287),
        ('Melisa', 'Moran', 'Melisa_Moran@birdseyeentertainment.com', 'Birdseye Entertainment', 161, 'DevOps Engineer', '2009-12-03', 0, 'moranme', null, 288),
        ('Hilario', 'Davis', 'Hilario_Davis@birdseyeentertainment.com', 'Birdseye Entertainment', 73, 'Senior Software Engineer', '2015-01-23', 0, 'davishi', null, 289),
        ('Glenda', 'Rush', 'Glenda_Rush@birdseyeentertainment.com', 'Birdseye Entertainment', 161, 'Senior Software Engineer', '2005-07-31', 0, 'rushgl', null, 290),
        ('Gale', 'Thompson', 'Gale_Thompson@birdseyeentertainment.com', 'Birdseye Entertainment', 104, 'Senior Software Engineer', '1998-06-10', 0, 'thompsonga', null, 291),
        ('Claudia', 'Holloway', 'Claudia_Holloway@birdseyeentertainment.com', 'Birdseye Entertainment', 111, 'Tech Lead', '1999-08-02', 0, 'hollowaycl', null, 292),
        ('Allyson', 'Coffey', 'Allyson_Coffey@birdseyeentertainment.com', 'Birdseye Entertainment', 116, 'DevOps Engineer', '1993-10-07', 0, 'coffeyal', null, 293),
        ('Burton', 'Vasquez', 'Burton_Vasquez@birdseyeentertainment.com', 'Birdseye Entertainment', 22, 'Software Engineer I', '1990-09-13', 0, 'vasquezbu', null, 294),
        ('Jake', 'Fox', 'Jake_Fox@birdseyeentertainment.com', 'Birdseye Entertainment', 114, 'Software Engineer II', '2005-02-21', 0, 'foxja', null, 295),
        ('Hassan', 'Sherman', 'Hassan_Sherman@birdseyeentertainment.com', 'Birdseye Entertainment', 146, 'Software Engineer I', '2013-08-24', 0, 'shermanha', null, 296),
        ('Olen', 'Marshall', 'Olen_Marshall@birdseyeentertainment.com', 'Birdseye Entertainment', 130, 'Principal Software Architect', '2017-12-13', 0, 'marshallol', null, 297),
        ('Dewey', 'Greene', 'Dewey_Greene@birdseyeentertainment.com', 'Birdseye Entertainment', 11, 'DevOps Engineer', '1998-08-01', 0, 'greenede', null, 298),
        ('Justin', 'Webb', 'Justin_Webb@birdseyeentertainment.com', 'Birdseye Entertainment', 159, 'Software Architect', '2006-06-05', 0, 'webbju', null, 299),
        ('Craig', 'Palmer', 'Craig_Palmer@birdseyeentertainment.com', 'Birdseye Entertainment', 69, 'Software Architect', '2009-11-13', 0, 'palmercr', null, 300),
        ('Darla', 'Murphy', 'Darla_Murphy@birdseyeentertainment.com', 'Birdseye Entertainment', 62, 'Site Reliability Engineer', '2014-11-10', 0, 'murphyda', null, 301),
        ('Elinor', 'Weiss', 'Elinor_Weiss@birdseyeentertainment.com', 'Birdseye Entertainment', 49, 'DevOps Engineer', '1992-01-09', 0, 'weissel', null, 302),
        ('Fletcher', 'Harrell', 'Fletcher_Harrell@birdseyeentertainment.com', 'Birdseye Entertainment', 161, 'Principal Software Architect', '2000-06-13', 0, 'harrellfl', null, 303),
        ('Ellsworth', 'Hull', 'Ellsworth_Hull@birdseyeentertainment.com', 'Birdseye Entertainment', 7, 'Principal Software Architect', '2013-03-20', 0, 'hullel', null, 304),
        ('Jannie', 'Watson', 'Jannie_Watson@birdseyeentertainment.com', 'Birdseye Entertainment', 40, 'Senior Software Engineer', '2012-08-31', 0, 'watsonja', null, 305),
        ('Tonya', 'Salas', 'Tonya_Salas@birdseyeentertainment.com', 'Birdseye Entertainment', 27, 'Senior Software Engineer', '2017-01-06', 0, 'salasto', null, 306),
        ('Young', 'Holland', 'Young_Holland@birdseyeentertainment.com', 'Birdseye Entertainment', 21, 'Principal Software Architect', '2010-01-30', 0, 'hollandyo', null, 307),
        ('Clayton', 'Houston', 'Clayton_Houston@birdseyeentertainment.com', 'Birdseye Entertainment', 6, 'DevOps Engineer', '2009-08-24', 0, 'houstoncl', null, 308),
        ('Eddy', 'Hess', 'Eddy_Hess@birdseyeentertainment.com', 'Birdseye Entertainment', 57, 'Software Engineer I', '2005-12-14', 0, 'hessed', null, 309),
        ('Joesph', 'Rose', 'Joesph_Rose@birdseyeentertainment.com', 'Birdseye Entertainment', 27, 'DevOps Engineer', '1992-01-27', 0, 'rosejo', null, 310),
        ('Lilly', 'Vazquez', 'Lilly_Vazquez@birdseyeentertainment.com', 'Birdseye Entertainment', 51, 'Software Engineer II', '2017-11-22', 0, 'vazquezli', null, 311),
        ('Karla', 'Nelson', 'Karla_Nelson@birdseyeentertainment.com', 'Birdseye Entertainment', 147, 'Software Engineer I', '2002-09-24', 0, 'nelsonka', null, 312),
        ('Elmo', 'Macias', 'Elmo_Macias@birdseyeentertainment.com', 'Birdseye Entertainment', 47, 'Tech Lead', '2015-01-21', 0, 'maciasel', null, 313),
        ('Marjorie', 'Blackburn', 'Marjorie_Blackburn@birdseyeentertainment.com', 'Birdseye Entertainment', 20, 'Tech Lead', '2018-09-29', 0, 'blackburnma', null, 314),
        ('Norbert', 'Jarvis', 'Norbert_Jarvis@birdseyeentertainment.com', 'Birdseye Entertainment', 72, 'Software Engineer II', '2004-02-27', 0, 'jarvisno', null, 315),
        ('Scottie', 'Rubio', 'Scottie_Rubio@birdseyeentertainment.com', 'Birdseye Entertainment', 18, 'Software Engineer I', '1996-10-29', 0, 'rubiosc', null, 316),
        ('Lorraine', 'Barber', 'Lorraine_Barber@birdseyeentertainment.com', 'Birdseye Entertainment', 101, 'Tech Lead', '2010-02-13', 0, 'barberlo', null, 317),
        ('Queen', 'Santana', 'Queen_Santana@birdseyeentertainment.com', 'Birdseye Entertainment', 38, 'Software Engineer II', '1998-10-13', 0, 'santanaqu', null, 318),
        ('Vincenzo', 'Ortiz', 'Vincenzo_Ortiz@birdseyeentertainment.com', 'Birdseye Entertainment', 47, 'Site Reliability Engineer', '2012-06-02', 0, 'ortizvi', null, 319),
        ('Maxwell', 'Mccann', 'Maxwell_Mccann@birdseyeentertainment.com', 'Birdseye Entertainment', 162, 'Software Architect', '2008-06-23', 0, 'mccannma', null, 320),
        ('John', 'Stout', 'John_Stout@birdseyeentertainment.com', 'Birdseye Entertainment', 47, 'Software Architect', '2012-01-28', 0, 'stoutjo', null, 321),
        ('Lakisha', 'Ramsey', 'Lakisha_Ramsey@birdseyeentertainment.com', 'Birdseye Entertainment', 147, 'Site Reliability Engineer', '2012-01-02', 0, 'ramseyla', null, 322),
        ('Faustino', 'Schwartz', 'Faustino_Schwartz@birdseyeentertainment.com', 'Birdseye Entertainment', 132, 'Software Architect', '1995-07-29', 0, 'schwartzfa', null, 323),
        ('Minerva', 'Lynn', 'Minerva_Lynn@birdseyeentertainment.com', 'Birdseye Entertainment', 165, 'Tech Lead', '2009-01-30', 0, 'lynnmi', null, 324),
        ('Darell', 'Cameron', 'Darell_Cameron@birdseyeentertainment.com', 'Birdseye Entertainment', 27, 'DevOps Engineer', '2016-01-30', 0, 'cameronda', null, 325),
        ('Katrina', 'Bird', 'Katrina_Bird@birdseyeentertainment.com', 'Birdseye Entertainment', 7, 'Software Engineer I', '1994-03-13', 0, 'birdka', null, 326),
        ('Sherrie', 'Martinez', 'Sherrie_Martinez@birdseyeentertainment.com', 'Birdseye Entertainment', 62, 'Software Architect', '2012-04-20', 0, 'martinezsh', null, 327),
        ('Freddie', 'Lloyd', 'Freddie_Lloyd@birdseyeentertainment.com', 'Birdseye Entertainment', 154, 'Principal Software Architect', '2001-04-07', 0, 'lloydfr', null, 328),
        ('Lindsay', 'Ward', 'Lindsay_Ward@birdseyeentertainment.com', 'Birdseye Entertainment', 166, 'Site Reliability Engineer', '2007-10-26', 0, 'wardli', null, 329),
        ('Colby', 'Sanford', 'Colby_Sanford@birdseyeentertainment.com', 'Birdseye Entertainment', 162, 'Senior Software Engineer', '2006-06-29', 0, 'sanfordco', null, 330),
        ('Jules', 'Pham', 'Jules_Pham@birdseyeentertainment.com', 'Birdseye Entertainment', 4, 'Senior Software Engineer', '1997-04-09', 0, 'phamju', null, 331),
        ('Warner', 'Fritz', 'Warner_Fritz@birdseyeentertainment.com', 'Birdseye Entertainment', 67, 'Tech Lead', '2010-12-20', 0, 'fritzwa', null, 332),
        ('Kerry', 'Farmer', 'Kerry_Farmer@birdseyeentertainment.com', 'Birdseye Entertainment', 89, 'Software Engineer I', '1998-03-28', 0, 'farmerke', null, 333),
        ('Alonzo', 'Solomon', 'Alonzo_Solomon@birdseyeentertainment.com', 'Birdseye Entertainment', 163, 'Senior Software Engineer', '2002-01-19', 0, 'solomonal', null, 334),
        ('Garfield', 'Payne', 'Garfield_Payne@birdseyeentertainment.com', 'Birdseye Entertainment', 163, 'Site Reliability Engineer', '1991-02-03', 0, 'paynega', null, 335),
        ('Pierre', 'Sherman', 'Pierre_Sherman@birdseyeentertainment.com', 'Birdseye Entertainment', 71, 'Site Reliability Engineer', '1990-03-22', 0, 'shermanpi', null, 336),
        ('Hilario', 'Atkins', 'Hilario_Atkins@birdseyeentertainment.com', 'Birdseye Entertainment', 18, 'Principal Software Architect', '1996-09-18', 0, 'atkinshi', null, 337),
        ('Ted', 'Forbes', 'Ted_Forbes@birdseyeentertainment.com', 'Birdseye Entertainment', 146, 'Software Architect', '2011-11-03', 0, 'forbeste', null, 338),
        ('Cecelia', 'Herring', 'Cecelia_Herring@birdseyeentertainment.com', 'Birdseye Entertainment', 89, 'Site Reliability Engineer', '1990-04-19', 0, 'herringce', null, 339),
        ('Noble', 'Velazquez', 'Noble_Velazquez@birdseyeentertainment.com', 'Birdseye Entertainment', 54, 'DevOps Engineer', '2002-12-02', 0, 'velazquezno', null, 340),
        ('Fanny', 'Brandt', 'Fanny_Brandt@birdseyeentertainment.com', 'Birdseye Entertainment', 122, 'Software Architect', '2017-10-28', 0, 'brandtfa', null, 341),
        ('Danilo', 'Hancock', 'Danilo_Hancock@birdseyeentertainment.com', 'Birdseye Entertainment', 13, 'Senior Software Engineer', '2011-02-13', 0, 'hancockda', null, 342),
        ('Ola', 'Rojas', 'Ola_Rojas@birdseyeentertainment.com', 'Birdseye Entertainment', 140, 'Software Engineer II', '2009-10-01', 0, 'rojasol', null, 343),
        ('Seymour', 'Crawford', 'Seymour_Crawford@birdseyeentertainment.com', 'Birdseye Entertainment', 104, 'Principal Software Architect', '2000-12-31', 0, 'crawfordse', null, 344),
        ('Mavis', 'Aguilar', 'Mavis_Aguilar@birdseyeentertainment.com', 'Birdseye Entertainment', 140, 'Tech Lead', '2008-05-25', 0, 'aguilarma', null, 345),
        ('Branden', 'Jacobs', 'Branden_Jacobs@birdseyeentertainment.com', 'Birdseye Entertainment', 141, 'Principal Software Architect', '1993-06-12', 0, 'jacobsbr', null, 346),
        ('Michele', 'Wiggins', 'Michele_Wiggins@birdseyeentertainment.com', 'Birdseye Entertainment', 94, 'Principal Software Architect', '2017-11-30', 0, 'wigginsmi', null, 347),
        ('Mai', 'Hobbs', 'Mai_Hobbs@birdseyeentertainment.com', 'Birdseye Entertainment', 52, 'Principal Software Architect', '2002-04-07', 0, 'hobbsma', null, 348),
        ('Lucas', 'Massey', 'Lucas_Massey@birdseyeentertainment.com', 'Birdseye Entertainment', 66, 'Tech Lead', '2015-02-25', 0, 'masseylu', null, 349),
        ('Calvin', 'Aguilar', 'Calvin_Aguilar@birdseyeentertainment.com', 'Birdseye Entertainment', 117, 'Tech Lead', '1994-07-08', 0, 'aguilarca', null, 350),
        ('Luella', 'Reynolds', 'Luella_Reynolds@birdseyeentertainment.com', 'Birdseye Entertainment', 166, 'Software Engineer I', '2005-12-05', 0, 'reynoldslu', null, 351),
        ('Alyson', 'Lynn', 'Alyson_Lynn@birdseyeentertainment.com', 'Birdseye Entertainment', 131, 'Software Engineer II', '1992-12-03', 0, 'lynnal', null, 352),
        ('Orville', 'Jacobson', 'Orville_Jacobson@birdseyeentertainment.com', 'Birdseye Entertainment', 82, 'DevOps Engineer', '2010-01-23', 0, 'jacobsonor', null, 353),
        ('Philip', 'Monroe', 'Philip_Monroe@birdseyeentertainment.com', 'Birdseye Entertainment', 140, 'Tech Lead', '2005-05-06', 0, 'monroeph', null, 354),
        ('Ted', 'Ayala', 'Ted_Ayala@birdseyeentertainment.com', 'Birdseye Entertainment', 105, 'DevOps Engineer', '2009-03-12', 0, 'ayalate', null, 355),
        ('Audrey', 'Fry', 'Audrey_Fry@birdseyeentertainment.com', 'Birdseye Entertainment', 154, 'Software Engineer II', '1998-05-02', 0, 'fryau', null, 356),
        ('Harris', 'Huff', 'Harris_Huff@birdseyeentertainment.com', 'Birdseye Entertainment', 136, 'Software Engineer II', '2003-07-18', 0, 'huffha', null, 357),
        ('Wm', 'Webb', 'Wm_Webb@birdseyeentertainment.com', 'Birdseye Entertainment', 52, 'Site Reliability Engineer', '2009-03-20', 0, 'webbwm', null, 358),
        ('Madge', 'Ritter', 'Madge_Ritter@birdseyeentertainment.com', 'Birdseye Entertainment', 21, 'Senior Software Engineer', '1997-10-04', 0, 'ritterma', null, 359),
        ('Lowell', 'Jensen', 'Lowell_Jensen@birdseyeentertainment.com', 'Birdseye Entertainment', 18, 'DevOps Engineer', '1998-08-22', 0, 'jensenlo', null, 360),
        ('Eula', 'Cardenas', 'Eula_Cardenas@birdseyeentertainment.com', 'Birdseye Entertainment', 25, 'Software Engineer I', '1993-03-05', 0, 'cardenaseu', null, 361),
        ('Brice', 'Perez', 'Brice_Perez@birdseyeentertainment.com', 'Birdseye Entertainment', 162, 'Software Engineer I', '1995-11-08', 0, 'perezbr', null, 362),
        ('Kristie', 'Buckley', 'Kristie_Buckley@birdseyeentertainment.com', 'Birdseye Entertainment', 122, 'Software Engineer II', '2013-10-14', 0, 'buckleykr', null, 363),
        ('Beverly', 'Bright', 'Beverly_Bright@birdseyeentertainment.com', 'Birdseye Entertainment', 67, 'DevOps Engineer', '2012-03-23', 0, 'brightbe', null, 364),
        ('Cordell', 'Frost', 'Cordell_Frost@birdseyeentertainment.com', 'Birdseye Entertainment', 29, 'Software Engineer II', '1993-01-11', 0, 'frostco', null, 365),
        ('Abby', 'Scott', 'Abby_Scott@birdseyeentertainment.com', 'Birdseye Entertainment', 21, 'Software Architect', '1990-05-07', 0, 'scottab', null, 366),
        ('Loretta', 'Marquez', 'Loretta_Marquez@birdseyeentertainment.com', 'Birdseye Entertainment', 57, 'Software Engineer I', '2018-08-13', 0, 'marquezlo', null, 367),
        ('Jane', 'Hansen', 'Jane_Hansen@birdseyeentertainment.com', 'Birdseye Entertainment', 92, 'DevOps Engineer', '1991-04-23', 0, 'hansenja', null, 368),
        ('Debra', 'Wiley', 'Debra_Wiley@birdseyeentertainment.com', 'Birdseye Entertainment', 121, 'Senior Software Engineer', '2013-03-24', 0, 'wileyde', null, 369),
        ('Issac', 'Byrd', 'Issac_Byrd@birdseyeentertainment.com', 'Birdseye Entertainment', 137, 'Software Engineer II', '1999-04-23', 0, 'byrdis', null, 370),
        ('Nina', 'Hudson', 'Nina_Hudson@birdseyeentertainment.com', 'Birdseye Entertainment', 30, 'Senior Software Engineer', '1999-05-05', 0, 'hudsonni', null, 371),
        ('Gale', 'Flowers', 'Gale_Flowers@birdseyeentertainment.com', 'Birdseye Entertainment', 29, 'Software Engineer I', '2010-05-20', 0, 'flowersga', null, 372),
        ('Alana', 'Le', 'Alana_Le@birdseyeentertainment.com', 'Birdseye Entertainment', 2, 'Site Reliability Engineer', '1997-02-05', 0, 'leal', null, 373),
        ('Carol', 'Acevedo', 'Carol_Acevedo@birdseyeentertainment.com', 'Birdseye Entertainment', 11, 'Tech Lead', '2005-10-02', 0, 'acevedoca', null, 374),
        ('Jc', 'Berger', 'Jc_Berger@birdseyeentertainment.com', 'Birdseye Entertainment', 36, 'Software Engineer I', '1990-05-02', 0, 'bergerjc', null, 375),
        ('Latoya', 'Roberts', 'Latoya_Roberts@birdseyeentertainment.com', 'Birdseye Entertainment', 106, 'Software Engineer I', '1997-04-23', 0, 'robertsla', null, 376),
        ('Sallie', 'Lambert', 'Sallie_Lambert@birdseyeentertainment.com', 'Birdseye Entertainment', 33, 'Tech Lead', '2016-02-13', 0, 'lambertsa', null, 377),
        ('Dixie', 'Hancock', 'Dixie_Hancock@birdseyeentertainment.com', 'Birdseye Entertainment', 162, 'Senior Software Engineer', '1998-03-07', 0, 'hancockdi', null, 378),
        ('Eddie', 'Cameron', 'Eddie_Cameron@birdseyeentertainment.com', 'Birdseye Entertainment', 109, 'Software Engineer II', '2012-04-29', 0, 'cameroned', null, 379),
        ('Burt', 'Archer', 'Burt_Archer@birdseyeentertainment.com', 'Birdseye Entertainment', 80, 'DevOps Engineer', '1999-12-14', 0, 'archerbu', null, 380),
        ('Sybil', 'Stout', 'Sybil_Stout@birdseyeentertainment.com', 'Birdseye Entertainment', 62, 'Senior Software Engineer', '1995-01-12', 0, 'stoutsy', null, 381),
        ('Weldon', 'Herring', 'Weldon_Herring@birdseyeentertainment.com', 'Birdseye Entertainment', 66, 'Principal Software Architect', '2007-03-17', 0, 'herringwe', null, 382),
        ('Pat', 'Henry', 'Pat_Henry@birdseyeentertainment.com', 'Birdseye Entertainment', 89, 'Senior Software Engineer', '1992-09-09', 0, 'henrypa', null, 383),
        ('Reba', 'Acevedo', 'Reba_Acevedo@birdseyeentertainment.com', 'Birdseye Entertainment', 11, 'Senior Software Engineer', '1996-10-31', 0, 'acevedore', null, 384),
        ('Geraldine', 'Steele', 'Geraldine_Steele@birdseyeentertainment.com', 'Birdseye Entertainment', 116, 'Tech Lead', '1999-12-15', 0, 'steelege', null, 385),
        ('Reggie', 'Sanchez', 'Reggie_Sanchez@birdseyeentertainment.com', 'Birdseye Entertainment', 30, 'Software Architect', '2007-11-26', 0, 'sanchezre', null, 386),
        ('Elvin', 'Stewart', 'Elvin_Stewart@birdseyeentertainment.com', 'Birdseye Entertainment', 66, 'Software Engineer II', '2006-04-29', 0, 'stewartel', null, 387),
        ('Mose', 'Cooper', 'Mose_Cooper@birdseyeentertainment.com', 'Birdseye Entertainment', 125, 'Software Engineer I', '2010-06-03', 0, 'coopermo', null, 388),
        ('Kyle', 'Duarte', 'Kyle_Duarte@birdseyeentertainment.com', 'Birdseye Entertainment', 106, 'Software Architect', '2008-07-22', 0, 'duarteky', null, 389),
        ('Giovanni', 'Clark', 'Giovanni_Clark@birdseyeentertainment.com', 'Birdseye Entertainment', 56, 'Software Engineer II', '2018-03-16', 0, 'clarkgi', null, 390),
        ('Erich', 'Horn', 'Erich_Horn@birdseyeentertainment.com', 'Birdseye Entertainment', 10, 'Site Reliability Engineer', '1998-05-13', 0, 'horner', null, 391),
        ('Tamera', 'Mccormick', 'Tamera_Mccormick@birdseyeentertainment.com', 'Birdseye Entertainment', 156, 'Software Architect', '2012-08-09', 0, 'mccormickta', null, 392),
        ('Bettie', 'Webster', 'Bettie_Webster@birdseyeentertainment.com', 'Birdseye Entertainment', 115, 'Software Architect', '2001-09-07', 0, 'websterbe', null, 393),
        ('Earlene', 'Snow', 'Earlene_Snow@birdseyeentertainment.com', 'Birdseye Entertainment', 146, 'Site Reliability Engineer', '2014-07-29', 0, 'snowea', null, 394),
        ('Hershel', 'Elliott', 'Hershel_Elliott@birdseyeentertainment.com', 'Birdseye Entertainment', 12, 'Software Engineer II', '2007-01-11', 0, 'elliotthe', null, 395),
        ('Rupert', 'Chan', 'Rupert_Chan@birdseyeentertainment.com', 'Birdseye Entertainment', 68, 'Software Engineer II', '1996-03-13', 0, 'chanru', null, 396),
        ('Latisha', 'Cardenas', 'Latisha_Cardenas@birdseyeentertainment.com', 'Birdseye Entertainment', 113, 'Software Engineer II', '2001-09-24', 0, 'cardenasla', null, 397),
        ('Rubin', 'Barker', 'Rubin_Barker@birdseyeentertainment.com', 'Birdseye Entertainment', 96, 'Principal Software Architect', '1993-07-18', 0, 'barkerru', null, 398),
        ('Marcie', 'Pollard', 'Marcie_Pollard@birdseyeentertainment.com', 'Birdseye Entertainment', 27, 'Principal Software Architect', '1993-02-17', 0, 'pollardma', null, 399),
        ('Candace', 'Bass', 'Candace_Bass@birdseyeentertainment.com', 'Birdseye Entertainment', 120, 'Software Engineer II', '2018-11-05', 0, 'bassca', null, 400),
        ('Danielle', 'Pennington', 'Danielle_Pennington@birdseyeentertainment.com', 'Birdseye Entertainment', 121, 'Software Architect', '1993-06-17', 0, 'penningtonda', null, 401),
        ('Evangeline', 'Taylor', 'Evangeline_Taylor@birdseyeentertainment.com', 'Birdseye Entertainment', 57, 'Principal Software Architect', '2014-04-17', 0, 'taylorev', null, 402),
        ('Natalie', 'Bentley', 'Natalie_Bentley@birdseyeentertainment.com', 'Birdseye Entertainment', 105, 'Software Engineer II', '2006-02-26', 0, 'bentleyna', null, 403),
        ('Marianne', 'Joyce', 'Marianne_Joyce@birdseyeentertainment.com', 'Birdseye Entertainment', 6, 'Senior Software Engineer', '2006-08-08', 0, 'joycema', null, 404),
        ('Forest', 'Orozco', 'Forest_Orozco@birdseyeentertainment.com', 'Birdseye Entertainment', 52, 'Software Engineer I', '2000-12-13', 0, 'orozcofo', null, 405),
        ('Jenny', 'Chandler', 'Jenny_Chandler@birdseyeentertainment.com', 'Birdseye Entertainment', 96, 'Software Engineer I', '2007-02-25', 0, 'chandlerje', null, 406),
        ('Ana', 'Barker', 'Ana_Barker@birdseyeentertainment.com', 'Birdseye Entertainment', 77, 'Site Reliability Engineer', '2016-08-30', 0, 'barkeran', null, 407),
        ('Sergio', 'Foley', 'Sergio_Foley@birdseyeentertainment.com', 'Birdseye Entertainment', 31, 'DevOps Engineer', '2017-12-15', 0, 'foleyse', null, 408),
        ('Karen', 'Buck', 'Karen_Buck@birdseyeentertainment.com', 'Birdseye Entertainment', 154, 'Software Engineer I', '1995-04-26', 0, 'buckka', null, 409),
        ('Horacio', 'Higgins', 'Horacio_Higgins@birdseyeentertainment.com', 'Birdseye Entertainment', 18, 'Tech Lead', '2001-03-29', 0, 'higginsho', null, 410),
        ('Rosario', 'Miles', 'Rosario_Miles@birdseyeentertainment.com', 'Birdseye Entertainment', 55, 'Software Engineer I', '2011-10-23', 0, 'milesro', null, 411),
        ('Gordon', 'Stanley', 'Gordon_Stanley@birdseyeentertainment.com', 'Birdseye Entertainment', 102, 'Senior Software Engineer', '2017-12-03', 0, 'stanleygo', null, 412),
        ('Ira', 'Warren', 'Ira_Warren@birdseyeentertainment.com', 'Birdseye Entertainment', 26, 'Site Reliability Engineer', '1992-02-04', 0, 'warrenir', null, 413),
        ('Liza', 'Conrad', 'Liza_Conrad@birdseyeentertainment.com', 'Birdseye Entertainment', 40, 'Principal Software Architect', '2018-11-05', 0, 'conradli', null, 414),
        ('Lacy', 'Bradley', 'Lacy_Bradley@birdseyeentertainment.com', 'Birdseye Entertainment', 81, 'Principal Software Architect', '2007-11-27', 0, 'bradleyla', null, 415),
        ('Delia', 'York', 'Delia_York@birdseyeentertainment.com', 'Birdseye Entertainment', 162, 'Principal Software Architect', '2002-07-12', 0, 'yorkde', null, 416),
        ('Jesus', 'Hutchinson', 'Jesus_Hutchinson@birdseyeentertainment.com', 'Birdseye Entertainment', 23, 'Software Engineer I', '2001-08-06', 0, 'hutchinsonje', null, 417),
        ('Palmer', 'Valencia', 'Palmer_Valencia@birdseyeentertainment.com', 'Birdseye Entertainment', 8, 'Software Engineer II', '1996-01-31', 0, 'valenciapa', null, 418),
        ('Dana', 'Bolton', 'Dana_Bolton@birdseyeentertainment.com', 'Birdseye Entertainment', 4, 'Tech Lead', '1996-10-26', 0, 'boltonda', null, 419),
        ('Jewell', 'Rich', 'Jewell_Rich@birdseyeentertainment.com', 'Birdseye Entertainment', 70, 'Tech Lead', '2006-09-28', 0, 'richje', null, 420),
        ('Rosalyn', 'Fuller', 'Rosalyn_Fuller@birdseyeentertainment.com', 'Birdseye Entertainment', 155, 'DevOps Engineer', '2002-01-14', 0, 'fullerro', null, 421),
        ('Maxine', 'Clarke', 'Maxine_Clarke@birdseyeentertainment.com', 'Birdseye Entertainment', 109, 'Site Reliability Engineer', '2012-04-21', 0, 'clarkema', null, 422),
        ('Boyd', 'Solomon', 'Boyd_Solomon@birdseyeentertainment.com', 'Birdseye Entertainment', 41, 'Tech Lead', '1998-10-12', 0, 'solomonbo', null, 423),
        ('Carrol', 'Conrad', 'Carrol_Conrad@birdseyeentertainment.com', 'Birdseye Entertainment', 94, 'Site Reliability Engineer', '2017-09-08', 0, 'conradca', null, 424),
        ('Domenic', 'Fields', 'Domenic_Fields@birdseyeentertainment.com', 'Birdseye Entertainment', 84, 'DevOps Engineer', '2009-05-10', 0, 'fieldsdo', null, 425),
        ('Jere', 'Schultz', 'Jere_Schultz@birdseyeentertainment.com', 'Birdseye Entertainment', 146, 'DevOps Engineer', '2008-09-23', 0, 'schultzje', null, 426),
        ('Reginald', 'Duke', 'Reginald_Duke@birdseyeentertainment.com', 'Birdseye Entertainment', 134, 'Principal Software Architect', '1996-06-17', 0, 'dukere', null, 427),
        ('Bud', 'Moss', 'Bud_Moss@birdseyeentertainment.com', 'Birdseye Entertainment', 132, 'DevOps Engineer', '2008-01-06', 0, 'mossbu', null, 428),
        ('Wilson', 'Figueroa', 'Wilson_Figueroa@birdseyeentertainment.com', 'Birdseye Entertainment', 68, 'Principal Software Architect', '2012-12-20', 0, 'figueroawi', null, 429),
        ('Brittany', 'Underwood', 'Brittany_Underwood@birdseyeentertainment.com', 'Birdseye Entertainment', 148, 'Software Engineer I', '2006-09-02', 0, 'underwoodbr', null, 430),
        ('Quinton', 'Hill', 'Quinton_Hill@birdseyeentertainment.com', 'Birdseye Entertainment', 146, 'DevOps Engineer', '1999-05-02', 0, 'hillqu', null, 431),
        ('Sammie', 'Moon', 'Sammie_Moon@birdseyeentertainment.com', 'Birdseye Entertainment', 147, 'Software Architect', '2002-01-15', 0, 'moonsa', null, 432),
        ('Joe', 'Day', 'Joe_Day@birdseyeentertainment.com', 'Birdseye Entertainment', 66, 'Senior Software Engineer', '2001-05-20', 0, 'dayjo', null, 433),
        ('Hayden', 'Hudson', 'Hayden_Hudson@birdseyeentertainment.com', 'Birdseye Entertainment', 146, 'Site Reliability Engineer', '2016-06-06', 0, 'hudsonha', null, 434),
        ('Aida', 'Mccarthy', 'Aida_Mccarthy@birdseyeentertainment.com', 'Birdseye Entertainment', 105, 'Principal Software Architect', '1992-01-24', 0, 'mccarthyai', null, 435),
        ('Petra', 'Newton', 'Petra_Newton@birdseyeentertainment.com', 'Birdseye Entertainment', 6, 'Senior Software Engineer', '1993-11-25', 0, 'newtonpe', null, 436),
        ('Faustino', 'Melendez', 'Faustino_Melendez@birdseyeentertainment.com', 'Birdseye Entertainment', 131, 'Software Engineer I', '2001-07-12', 0, 'melendezfa', null, 437),
        ('Lidia', 'Davila', 'Lidia_Davila@birdseyeentertainment.com', 'Birdseye Entertainment', 81, 'Principal Software Architect', '2016-03-09', 0, 'davilali', null, 438),
        ('Thurman', 'Hubbard', 'Thurman_Hubbard@birdseyeentertainment.com', 'Birdseye Entertainment', 11, 'Software Architect', '2014-08-24', 0, 'hubbardth', null, 439),
        ('Marcos', 'Walton', 'Marcos_Walton@birdseyeentertainment.com', 'Birdseye Entertainment', 85, 'Principal Software Architect', '2003-02-24', 0, 'waltonma', null, 440),
        ('Ben', 'Marks', 'Ben_Marks@birdseyeentertainment.com', 'Birdseye Entertainment', 52, 'Site Reliability Engineer', '2011-12-24', 0, 'marksbe', null, 441),
        ('Robyn', 'Church', 'Robyn_Church@birdseyeentertainment.com', 'Birdseye Entertainment', 105, 'Site Reliability Engineer', '1990-06-29', 0, 'churchro', null, 442),
        ('Joseph', 'Barry', 'Joseph_Barry@birdseyeentertainment.com', 'Birdseye Entertainment', 4, 'Tech Lead', '1995-01-18', 0, 'barryjo', null, 443),
        ('Clinton', 'Hensley', 'Clinton_Hensley@birdseyeentertainment.com', 'Birdseye Entertainment', 42, 'Site Reliability Engineer', '1999-03-01', 0, 'hensleycl', null, 444),
        ('Long', 'Stevens', 'Long_Stevens@birdseyeentertainment.com', 'Birdseye Entertainment', 75, 'Software Engineer II', '2004-07-07', 0, 'stevenslo', null, 445),
        ('Gail', 'Flores', 'Gail_Flores@birdseyeentertainment.com', 'Birdseye Entertainment', 62, 'Tech Lead', '1990-03-13', 0, 'floresga', null, 446),
        ('Jordon', 'Brennan', 'Jordon_Brennan@birdseyeentertainment.com', 'Birdseye Entertainment', 88, 'DevOps Engineer', '2008-04-20', 0, 'brennanjo', null, 447),
        ('Brett', 'Bradley', 'Brett_Bradley@birdseyeentertainment.com', 'Birdseye Entertainment', 158, 'Software Architect', '1993-10-14', 0, 'bradleybr', null, 448),
        ('Kevin', 'Pruitt', 'Kevin_Pruitt@birdseyeentertainment.com', 'Birdseye Entertainment', 142, 'Software Architect', '1992-07-19', 0, 'pruittke', null, 449),
        ('Amado', 'Delacruz', 'Amado_Delacruz@birdseyeentertainment.com', 'Birdseye Entertainment', 106, 'Software Architect', '1993-05-20', 0, 'delacruzam', null, 450),
        ('Leila', 'Delgado', 'Leila_Delgado@birdseyeentertainment.com', 'Birdseye Entertainment', 85, 'Principal Software Architect', '1995-05-24', 0, 'delgadole', null, 451),
        ('Isreal', 'Farley', 'Isreal_Farley@birdseyeentertainment.com', 'Birdseye Entertainment', 73, 'Senior Software Engineer', '1999-12-07', 0, 'farleyis', null, 452),
        ('Lowell', 'Petersen', 'Lowell_Petersen@birdseyeentertainment.com', 'Birdseye Entertainment', 144, 'Software Architect', '1998-06-30', 0, 'petersenlo', null, 453),
        ('Carolyn', 'Avery', 'Carolyn_Avery@birdseyeentertainment.com', 'Birdseye Entertainment', 91, 'Senior Software Engineer', '2012-10-29', 0, 'averyca', null, 454),
        ('Cyril', 'Franco', 'Cyril_Franco@birdseyeentertainment.com', 'Birdseye Entertainment', 22, 'Software Architect', '1993-07-15', 0, 'francocy', null, 455),
        ('Lizzie', 'Pennington', 'Lizzie_Pennington@birdseyeentertainment.com', 'Birdseye Entertainment', 112, 'Software Engineer II', '1992-12-18', 0, 'penningtonli', null, 456),
        ('Sue', 'Heath', 'Sue_Heath@birdseyeentertainment.com', 'Birdseye Entertainment', 129, 'Software Engineer I', '2009-12-15', 0, 'heathsu', null, 457),
        ('Hilton', 'Gates', 'Hilton_Gates@birdseyeentertainment.com', 'Birdseye Entertainment', 145, 'Principal Software Architect', '2012-02-15', 0, 'gateshi', null, 458),
        ('Elaine', 'Skinner', 'Elaine_Skinner@birdseyeentertainment.com', 'Birdseye Entertainment', 29, 'Senior Software Engineer', '1993-05-20', 0, 'skinnerel', null, 459),
        ('Val', 'Mclean', 'Val_Mclean@birdseyeentertainment.com', 'Birdseye Entertainment', 162, 'DevOps Engineer', '2003-06-25', 0, 'mcleanva', null, 460),
        ('Peter', 'Rubio', 'Peter_Rubio@birdseyeentertainment.com', 'Birdseye Entertainment', 112, 'Tech Lead', '1998-02-04', 0, 'rubiope', null, 461),
        ('Carmelo', 'Powers', 'Carmelo_Powers@birdseyeentertainment.com', 'Birdseye Entertainment', 141, 'Principal Software Architect', '2016-05-08', 0, 'powersca', null, 462),
        ('Margery', 'Hurst', 'Margery_Hurst@birdseyeentertainment.com', 'Birdseye Entertainment', 118, 'Senior Software Engineer', '2014-04-24', 0, 'hurstma', null, 463),
        ('Louie', 'Wilson', 'Louie_Wilson@birdseyeentertainment.com', 'Birdseye Entertainment', 135, 'Software Engineer I', '2018-03-24', 0, 'wilsonlo', null, 464),
        ('Jodi', 'Odonnell', 'Jodi_Odonnell@birdseyeentertainment.com', 'Birdseye Entertainment', 105, 'Principal Software Architect', '2007-02-12', 0, 'odonnelljo', null, 465),
        ('Lilia', 'Knight', 'Lilia_Knight@birdseyeentertainment.com', 'Birdseye Entertainment', 126, 'Site Reliability Engineer', '2010-02-01', 0, 'knightli', null, 466),
        ('Young', 'Rios', 'Young_Rios@birdseyeentertainment.com', 'Birdseye Entertainment', 138, 'DevOps Engineer', '2013-03-12', 0, 'riosyo', null, 467);