insert into aki.position (description, min_year_experience, salary, is_posted, title, manager_id, id)
values  ('Entry level Software Engineering role on an Agile team', 0, 68496, 0, 'Software Engineer I', 89, 1),
        ('Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 157670, 0, 'Tech Lead', 124, 2),
        ('Entry level Software Engineering role on an Agile team', 0, 67582, 0, 'Software Engineer I', 42, 3),
        ('Responsible for application ownership and operation in production', 5, 132946, 0, 'Site Reliability Engineer', 134, 4),
        ('Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 181025, 0, 'Tech Lead', 144, 5),
        ('Entry level Software Engineering role on an Agile team', 0, 66308, 0, 'Software Engineer I', 103, 6),
        ('Entry level Software Engineering role on an Agile team', 0, 76549, 0, 'Software Engineer I', 96, 7),
        ('Senior Engineer for an agile development team.  Must have in depth knowledge of software systems and be able to learn quickly', 7, 137780, 0, 'Senior Software Engineer', 158, 8),
        ('Software Architect for software product.  Must be able to quickly design and demonstrate new architecture patterns and processes.', 10, 164054, 0, 'Software Architect', 53, 9),
        ('Entry level Software Engineering role on an Agile team', 0, 65202, 0, 'Software Engineer I', 142, 10),
        ('Lead the vision of future software architecture for the company', 10, 159900, 0, 'Principal Software Architect', 60, 11),
        ('Senior Engineer for an agile development team.  Must have in depth knowledge of software systems and be able to learn quickly', 7, 147503, 0, 'Senior Software Engineer', 69, 12),
        ('Support and automate development processes, deployments and more as a member of an Agile team.', 2, 71089, 0, 'DevOps Engineer', 90, 13),
        ('Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 121686, 0, 'Tech Lead', 53, 14),
        ('Support and automate development processes, deployments and more as a member of an Agile team.', 2, 75987, 0, 'DevOps Engineer', 5, 15),
        ('Lead the vision of future software architecture for the company', 10, 199635, 0, 'Principal Software Architect', 73, 16),
        ('Lead the vision of future software architecture for the company', 10, 169102, 0, 'Principal Software Architect', 146, 17),
        ('Senior Engineer for an agile development team.  Must have in depth knowledge of software systems and be able to learn quickly', 7, 147406, 0, 'Senior Software Engineer', 151, 18),
        ('Software Architect for software product.  Must be able to quickly design and demonstrate new architecture patterns and processes.', 10, 139373, 0, 'Software Architect', 45, 19),
        ('Responsible for application ownership and operation in production', 5, 94933, 0, 'Site Reliability Engineer', 9, 20),
        ('Software Architect for software product.  Must be able to quickly design and demonstrate new architecture patterns and processes.', 10, 146720, 0, 'Software Architect', 35, 21),
        ('Software Engineering role on an Agile team.', 3, 81036, 0, 'Software Engineer II', 12, 22),
        ('Lead the vision of future software architecture for the company', 10, 158938, 0, 'Principal Software Architect', 145, 23),
        ('Entry level Software Engineering role on an Agile team', 0, 64244, 0, 'Software Engineer I', 110, 24),
        ('Responsible for application ownership and operation in production', 5, 124353, 0, 'Site Reliability Engineer', 73, 25),
        ('Entry level Software Engineering role on an Agile team', 0, 77875, 0, 'Software Engineer I', 48, 26),
        ('Senior Engineer for an agile development team.  Must have in depth knowledge of software systems and be able to learn quickly', 7, 117472, 0, 'Senior Software Engineer', 126, 27),
        ('Responsible for application ownership and operation in production', 5, 109674, 0, 'Site Reliability Engineer', 45, 28),
        ('Senior Engineer for an agile development team.  Must have in depth knowledge of software systems and be able to learn quickly', 7, 120261, 0, 'Senior Software Engineer', 158, 29),
        ('Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 141751, 0, 'Tech Lead', 107, 30),
        ('Software Engineering role on an Agile team.', 3, 100813, 0, 'Software Engineer II', 8, 31),
        ('Responsible for application ownership and operation in production', 5, 108759, 0, 'Site Reliability Engineer', 50, 32),
        ('Responsible for application ownership and operation in production', 5, 90883, 0, 'Site Reliability Engineer', 47, 33),
        ('Lead the vision of future software architecture for the company', 10, 195322, 0, 'Principal Software Architect', 165, 34),
        ('Support and automate development processes, deployments and more as a member of an Agile team.', 2, 109628, 0, 'DevOps Engineer', 147, 35),
        ('Senior Engineer for an agile development team.  Must have in depth knowledge of software systems and be able to learn quickly', 7, 169383, 0, 'Senior Software Engineer', 117, 36),
        ('Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 179321, 0, 'Tech Lead', 35, 37),
        ('Entry level Software Engineering role on an Agile team', 0, 62810, 0, 'Software Engineer I', 101, 38),
        ('Lead the vision of future software architecture for the company', 10, 199065, 0, 'Principal Software Architect', 30, 39),
        ('Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 140292, 0, 'Tech Lead', 55, 40),
        ('Software Architect for software product.  Must be able to quickly design and demonstrate new architecture patterns and processes.', 10, 167058, 0, 'Software Architect', 47, 41),
        ('Entry level Software Engineering role on an Agile team', 0, 78128, 0, 'Software Engineer I', 47, 42),
        ('Lead the vision of future software architecture for the company', 10, 189395, 0, 'Principal Software Architect', 5, 43),
        ('Lead the vision of future software architecture for the company', 10, 149607, 0, 'Principal Software Architect', 16, 44),
        ('Entry level Software Engineering role on an Agile team', 0, 64149, 0, 'Software Engineer I', 23, 45),
        ('Lead the vision of future software architecture for the company', 10, 146387, 0, 'Principal Software Architect', 107, 46),
        ('Responsible for application ownership and operation in production', 5, 113885, 0, 'Site Reliability Engineer', 72, 47),
        ('Lead the vision of future software architecture for the company', 10, 199657, 0, 'Principal Software Architect', 1, 48),
        ('Software Engineering role on an Agile team.', 3, 104684, 0, 'Software Engineer II', 160, 49),
        ('Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 169643, 0, 'Tech Lead', 46, 50);