insert into aki.position (id, description, min_year_experience, salary, is_posted, title, employee_id)
values  (1, 'Entry level Software Engineering role on an Agile team', 0, 67848, 0, 'Software Engineer I', null),
        (2, 'Software Architect for software product.  Must be able to quickly design and demonstrate new architecture patterns and processes.', 10, 151366, 0, 'Software Architect', null),
        (3, 'Software Engineering role on an Agile team.', 3, 77927, 0, 'Software Engineer II', null),
        (4, 'Software Architect for software product.  Must be able to quickly design and demonstrate new architecture patterns and processes.', 10, 152811, 0, 'Software Architect', null),
        (5, 'Software Engineering role on an Agile team.', 3, 80235, 0, 'Software Engineer II', null),
        (6, 'Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 133558, 0, 'Tech Lead', null),
        (7, 'Software Engineering role on an Agile team.', 3, 114430, 0, 'Software Engineer II', null),
        (8, 'Support and automate development processes, deployments and more as a member of an Agile team.', 2, 78917, 0, 'DevOps Engineer', null),
        (9, 'Senior Engineer for an agile development team.  Must have in depth knowledge of software systems and be able to learn quickly', 7, 137780, 0, 'Senior Software Engineer', null),
        (10, 'Software Architect for software product.  Must be able to quickly design and demonstrate new architecture patterns and processes.', 10, 161215, 0, 'Software Architect', null),
        (11, 'Software Architect for software product.  Must be able to quickly design and demonstrate new architecture patterns and processes.', 10, 154986, 0, 'Software Architect', null),
        (12, 'Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 112382, 0, 'Tech Lead', null),
        (13, 'Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 183646, 0, 'Tech Lead', null),
        (14, 'Software Architect for software product.  Must be able to quickly design and demonstrate new architecture patterns and processes.', 10, 180483, 0, 'Software Architect', null),
        (15, 'Software Architect for software product.  Must be able to quickly design and demonstrate new architecture patterns and processes.', 10, 139096, 0, 'Software Architect', null),
        (16, 'Software Architect for software product.  Must be able to quickly design and demonstrate new architecture patterns and processes.', 10, 160536, 0, 'Software Architect', null),
        (17, 'Responsible for application ownership and operation in production', 5, 95447, 0, 'Site Reliability Engineer', null),
        (18, 'Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 123056, 0, 'Tech Lead', null),
        (19, 'Support and automate development processes, deployments and more as a member of an Agile team.', 2, 123168, 0, 'DevOps Engineer', null),
        (20, 'Responsible for application ownership and operation in production', 5, 118219, 0, 'Site Reliability Engineer', null),
        (21, 'Support and automate development processes, deployments and more as a member of an Agile team.', 2, 119857, 0, 'DevOps Engineer', null),
        (22, 'Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 141517, 0, 'Tech Lead', null),
        (23, 'Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 166012, 0, 'Tech Lead', null),
        (24, 'Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 134557, 0, 'Tech Lead', null),
        (25, 'Lead the vision of future software architecture for the company', 10, 183711, 0, 'Principal Software Architect', null),
        (26, 'Support and automate development processes, deployments and more as a member of an Agile team.', 2, 78643, 0, 'DevOps Engineer', null),
        (27, 'Responsible for application ownership and operation in production', 5, 110335, 0, 'Site Reliability Engineer', null),
        (28, 'Entry level Software Engineering role on an Agile team', 0, 77875, 0, 'Software Engineer I', null),
        (29, 'Lead the vision of future software architecture for the company', 10, 171723, 0, 'Principal Software Architect', null),
        (30, 'Support and automate development processes, deployments and more as a member of an Agile team.', 2, 104061, 0, 'DevOps Engineer', null),
        (31, 'Software Engineering role on an Agile team.', 3, 113886, 0, 'Software Engineer II', null),
        (32, 'Senior Engineer for an agile development team.  Must have in depth knowledge of software systems and be able to learn quickly', 7, 162406, 0, 'Senior Software Engineer', null),
        (33, 'Support and automate development processes, deployments and more as a member of an Agile team.', 2, 101190, 0, 'DevOps Engineer', null),
        (34, 'Responsible for application ownership and operation in production', 5, 114208, 0, 'Site Reliability Engineer', null),
        (35, 'Support and automate development processes, deployments and more as a member of an Agile team.', 2, 108714, 0, 'DevOps Engineer', null),
        (36, 'Support and automate development processes, deployments and more as a member of an Agile team.', 2, 121766, 0, 'DevOps Engineer', null),
        (37, 'Support and automate development processes, deployments and more as a member of an Agile team.', 2, 74760, 0, 'DevOps Engineer', null),
        (38, 'Lead the vision of future software architecture for the company', 10, 181532, 0, 'Principal Software Architect', null),
        (39, 'Entry level Software Engineering role on an Agile team', 0, 70259, 0, 'Software Engineer I', null),
        (40, 'Responsible for application ownership and operation in production', 5, 93402, 0, 'Site Reliability Engineer', null),
        (41, 'Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 133171, 0, 'Tech Lead', null),
        (42, 'Entry level Software Engineering role on an Agile team', 0, 70912, 0, 'Software Engineer I', null),
        (43, 'Software Architect for software product.  Must be able to quickly design and demonstrate new architecture patterns and processes.', 10, 180630, 0, 'Software Architect', null),
        (44, 'Software Engineering role on an Agile team.', 3, 76884, 0, 'Software Engineer II', null),
        (45, 'Software Architect for software product.  Must be able to quickly design and demonstrate new architecture patterns and processes.', 10, 162804, 0, 'Software Architect', null),
        (46, 'Responsible for application ownership and operation in production', 5, 138601, 0, 'Site Reliability Engineer', null),
        (47, 'Lead the vision of future software architecture for the company', 10, 149607, 0, 'Principal Software Architect', null),
        (48, 'Entry level Software Engineering role on an Agile team', 0, 76186, 0, 'Software Engineer I', null),
        (49, 'Entry level Software Engineering role on an Agile team', 0, 75145, 0, 'Software Engineer I', null),
        (50, 'Technical leader for an agile team.  Must show strong leadership skills, innovative problem solving, and deep knowledge of software systems.', 7, 115363, 0, 'Tech Lead', null);