insert into aki.tag (name, description, id)
values  ('SQL', null, 1),
        ('Kafka', null, 2),
        ('Kotlin', null, 3),
        ('Git', null, 4),
        ('Java', null, 5),
        ('Angular', null, 6),
        ('MongoDB', null, 7),
        ('MySQL', null, 8),
        ('Flink', null, 9),
        ('Jenkins', null, 10),
        ('Spark', null, 11),
        ('Python', null, 12),
        ('React', null, 13),
        ('JavaScript', null, 14),
        ('NodeJS', null, 15);